# Set up

In [1]:
project_folder = "/content/drive/MyDrive/weather_predictor"

from google.colab import drive
drive.mount('/content/drive')

%cd "{project_folder}"
!git pull

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/MyDrive/weather_predictor
Already up to date.

# Cài đặt môi trường

In [105]:
!git pull
!pip install -r requirements.txt

remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 3 (delta 2), reused 3 (delta 2), pack-reused 0 (from 0)
Unpacking objects: 100% (3/3), 270 bytes | 0 bytes/s, done.
From https://github.com/zalexdevon/weather_predictor
   4f5cb9b..04a90db  main       -> origin/main
Updating 4f5cb9b..04a90db
Fast-forward
 requirements.txt | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
Obtaining file:///content/drive/MyDrive/weather_predictor (from -r requirements.txt (line 16))
  Preparing metadata (setup.py) ... done
Requirement already satisfied: tensorflow in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 1)) (2.18.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 2)) (2.2.2)
Requirement already satisfied: numpy==1.26.4 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 3)) (1.26.4)
Requirement already satisfied: dvc in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 4)) (3.59.1)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 5)) (3.10.0)
Requirement already satisfied: notebook in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 6)) (6.5.7)
Requirement already satisfied: scikit-learn==1.3.0 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 7)) (1.3.0)
Requirement already satisfied: python-box==6.0.2 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 8)) (6.0.2)
Requirement already satisfied: pyYAML in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 9)) (6.0.2)
Requirement already satisfied: types-PyYAML in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 10)) (6.0.12.20250402)
Requirement already satisfied: seaborn in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 11)) (0.13.2)
Requirement already satisfied: xgboost in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 12)) (2.1.4)
Requirement already satisfied: lightgbm in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 13)) (4.5.0)
Requirement already satisfied: imbalanced-learn in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 14)) (0.12.4)
Collecting zzzz_mylib_23_4==0.29 (from -r requirements.txt (line 15))
  Downloading zzzz_mylib_23_4-0.29-py3-none-any.whl.metadata (174 bytes)
Requirement already satisfied: scipy>=1.5.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn==1.3.0->-r requirements.txt (line 7)) (1.14.1)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from scikit-learn==1.3.0->-r requirements.txt (line 7)) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn==1.3.0->-r requirements.txt (line 7)) (3.6.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow->-r requirements.txt (line 1)) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow->-r requirements.txt (line 1)) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.11/dist-packages (from tensorflow->-r requirements.txt (line 1)) (25.2.10)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow->-r requirements.txt (line 1)) (0.6.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow->-r requirements.txt (line 1)) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow->-r requirements.txt (line 1)) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.11/dist-packages (from tensorflow->-r requirements.txt (line 1)) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from tensorflow->-r requirements.txt (line 1)) (24.2)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in /usr/local/lib/python3.11/dist-packages (from tensorflow->-r requirements.txt (line 1)) (5.29.4)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow->-r requirements.txt (line 1)) (2.32.3)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (from tensorflow->-r requirements.txt (line 1)) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow->-r requirements.txt (line 1)) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow->-r requirements.txt (line 1)) (3.0.1)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.11/dist-packages (from tensorflow->-r requirements.txt (line 1)) (4.13.2)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow->-r requirements.txt (line 1)) (1.17.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.11/dist-packages (from tensorflow->-r requirements.txt (line 1)) (1.71.0)
Requirement already satisfied: tensorboard<2.19,>=2.18 in /usr/local/lib/python3.11/dist-packages (from tensorflow->-r requirements.txt (line 1)) (2.18.0)
Requirement already satisfied: keras>=3.5.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow->-r requirements.txt (line 1)) (3.8.0)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow->-r requirements.txt (line 1)) (3.13.0)
Requirement already satisfied: ml-dtypes<0.5.0,>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow->-r requirements.txt (line 1)) (0.4.1)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow->-r requirements.txt (line 1)) (0.37.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->-r requirements.txt (line 2)) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->-r requirements.txt (line 2)) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->-r requirements.txt (line 2)) (2025.2)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.11/dist-packages (from dvc->-r requirements.txt (line 4)) (25.3.0)
Requirement already satisfied: celery in /usr/local/lib/python3.11/dist-packages (from dvc->-r requirements.txt (line 4)) (5.5.2)
Requirement already satisfied: colorama>=0.3.9 in /usr/local/lib/python3.11/dist-packages (from dvc->-r requirements.txt (line 4)) (0.4.6)
Requirement already satisfied: configobj>=5.0.9 in /usr/local/lib/python3.11/dist-packages (from dvc->-r requirements.txt (line 4)) (5.0.9)
Requirement already satisfied: distro>=1.3 in /usr/local/lib/python3.11/dist-packages (from dvc->-r requirements.txt (line 4)) (1.9.0)
Requirement already satisfied: dpath<3,>=2.1.0 in /usr/local/lib/python3.11/dist-packages (from dvc->-r requirements.txt (line 4)) (2.2.0)
Requirement already satisfied: dulwich in /usr/local/lib/python3.11/dist-packages (from dvc->-r requirements.txt (line 4)) (0.22.8)
Requirement already satisfied: dvc-data<3.17,>=3.16.2 in /usr/local/lib/python3.11/dist-packages (from dvc->-r requirements.txt (line 4)) (3.16.9)
Requirement already satisfied: dvc-http>=2.29.0 in /usr/local/lib/python3.11/dist-packages (from dvc->-r requirements.txt (line 4)) (2.32.0)
Requirement already satisfied: dvc-objects in /usr/local/lib/python3.11/dist-packages (from dvc->-r requirements.txt (line 4)) (5.1.0)
Requirement already satisfied: dvc-render<2,>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from dvc->-r requirements.txt (line 4)) (1.0.2)
Requirement already satisfied: dvc-studio-client<1,>=0.21 in /usr/local/lib/python3.11/dist-packages (from dvc->-r requirements.txt (line 4)) (0.21.0)
Requirement already satisfied: dvc-task<1,>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from dvc->-r requirements.txt (line 4)) (0.40.2)
Requirement already satisfied: flatten_dict<1,>=0.4.1 in /usr/local/lib/python3.11/dist-packages (from dvc->-r requirements.txt (line 4)) (0.4.2)
Requirement already satisfied: flufl.lock<9,>=8.1.0 in /usr/local/lib/python3.11/dist-packages (from dvc->-r requirements.txt (line 4)) (8.1.0)
Requirement already satisfied: fsspec>=2024.2.0 in /usr/local/lib/python3.11/dist-packages (from dvc->-r requirements.txt (line 4)) (2025.3.2)
Requirement already satisfied: funcy>=1.14 in /usr/local/lib/python3.11/dist-packages (from dvc->-r requirements.txt (line 4)) (2.0)
Requirement already satisfied: grandalf<1,>=0.7 in /usr/local/lib/python3.11/dist-packages (from dvc->-r requirements.txt (line 4)) (0.8)
Requirement already satisfied: gto<2,>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from dvc->-r requirements.txt (line 4)) (1.7.2)
Requirement already satisfied: hydra-core>=1.1 in /usr/local/lib/python3.11/dist-packages (from dvc->-r requirements.txt (line 4)) (1.3.2)
Requirement already satisfied: iterative-telemetry>=0.0.7 in /usr/local/lib/python3.11/dist-packages (from dvc->-r requirements.txt (line 4)) (0.0.10)
Requirement already satisfied: kombu in /usr/local/lib/python3.11/dist-packages (from dvc->-r requirements.txt (line 4)) (5.5.3)
Requirement already satisfied: networkx>=2.5 in /usr/local/lib/python3.11/dist-packages (from dvc->-r requirements.txt (line 4)) (3.4.2)
Requirement already satisfied: omegaconf in /usr/local/lib/python3.11/dist-packages (from dvc->-r requirements.txt (line 4)) (2.3.0)
Requirement already satisfied: pathspec>=0.10.3 in /usr/local/lib/python3.11/dist-packages (from dvc->-r requirements.txt (line 4)) (0.12.1)
Requirement already satisfied: platformdirs<5,>=3.1.1 in /usr/local/lib/python3.11/dist-packages (from dvc->-r requirements.txt (line 4)) (4.3.7)
Requirement already satisfied: psutil>=5.8 in /usr/local/lib/python3.11/dist-packages (from dvc->-r requirements.txt (line 4)) (5.9.5)
Requirement already satisfied: pydot>=1.2.4 in /usr/local/lib/python3.11/dist-packages (from dvc->-r requirements.txt (line 4)) (3.0.4)
Requirement already satisfied: pygtrie>=2.3.2 in /usr/local/lib/python3.11/dist-packages (from dvc->-r requirements.txt (line 4)) (2.5.0)
Requirement already satisfied: pyparsing>=2.4.7 in /usr/local/lib/python3.11/dist-packages (from dvc->-r requirements.txt (line 4)) (3.2.3)
Requirement already satisfied: rich>=12 in /usr/local/lib/python3.11/dist-packages (from dvc->-r requirements.txt (line 4)) (13.9.4)
Requirement already satisfied: ruamel.yaml>=0.17.11 in /usr/local/lib/python3.11/dist-packages (from dvc->-r requirements.txt (line 4)) (0.18.10)
Requirement already satisfied: scmrepo<4,>=3.3.8 in /usr/local/lib/python3.11/dist-packages (from dvc->-r requirements.txt (line 4)) (3.3.10)
Requirement already satisfied: shortuuid>=0.5 in /usr/local/lib/python3.11/dist-packages (from dvc->-r requirements.txt (line 4)) (1.0.13)
Requirement already satisfied: shtab<2,>=1.3.4 in /usr/local/lib/python3.11/dist-packages (from dvc->-r requirements.txt (line 4)) (1.7.2)
Requirement already satisfied: tabulate>=0.8.7 in /usr/local/lib/python3.11/dist-packages (from dvc->-r requirements.txt (line 4)) (0.9.0)
Requirement already satisfied: tomlkit>=0.11.1 in /usr/local/lib/python3.11/dist-packages (from dvc->-r requirements.txt (line 4)) (0.13.2)
Requirement already satisfied: tqdm<5,>=4.63.1 in /usr/local/lib/python3.11/dist-packages (from dvc->-r requirements.txt (line 4)) (4.67.1)
Requirement already satisfied: voluptuous>=0.11.7 in /usr/local/lib/python3.11/dist-packages (from dvc->-r requirements.txt (line 4)) (0.15.2)
Requirement already satisfied: zc.lockfile>=1.2.1 in /usr/local/lib/python3.11/dist-packages (from dvc->-r requirements.txt (line 4)) (3.0.post1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->-r requirements.txt (line 5)) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib->-r requirements.txt (line 5)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->-r requirements.txt (line 5)) (4.57.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->-r requirements.txt (line 5)) (1.4.8)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.11/dist-packages (from matplotlib->-r requirements.txt (line 5)) (11.1.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from notebook->-r requirements.txt (line 6)) (3.1.6)
Requirement already satisfied: tornado>=6.1 in /usr/local/lib/python3.11/dist-packages (from notebook->-r requirements.txt (line 6)) (6.4.2)
Requirement already satisfied: pyzmq>=17 in /usr/local/lib/python3.11/dist-packages (from notebook->-r requirements.txt (line 6)) (24.0.1)
Requirement already satisfied: argon2-cffi in /usr/local/lib/python3.11/dist-packages (from notebook->-r requirements.txt (line 6)) (23.1.0)
Requirement already satisfied: traitlets>=4.2.1 in /usr/local/lib/python3.11/dist-packages (from notebook->-r requirements.txt (line 6)) (5.7.1)
Requirement already satisfied: jupyter-core>=4.6.1 in /usr/local/lib/python3.11/dist-packages (from notebook->-r requirements.txt (line 6)) (5.7.2)
Requirement already satisfied: jupyter-client<8,>=5.3.4 in /usr/local/lib/python3.11/dist-packages (from notebook->-r requirements.txt (line 6)) (6.1.12)
Requirement already satisfied: ipython-genutils in /usr/local/lib/python3.11/dist-packages (from notebook->-r requirements.txt (line 6)) (0.2.0)
Requirement already satisfied: nbformat in /usr/local/lib/python3.11/dist-packages (from notebook->-r requirements.txt (line 6)) (5.10.4)
Requirement already satisfied: nbconvert>=5 in /usr/local/lib/python3.11/dist-packages (from notebook->-r requirements.txt (line 6)) (7.16.6)
Requirement already satisfied: nest-asyncio>=1.5 in /usr/local/lib/python3.11/dist-packages (from notebook->-r requirements.txt (line 6)) (1.6.0)
Requirement already satisfied: ipykernel in /usr/local/lib/python3.11/dist-packages (from notebook->-r requirements.txt (line 6)) (6.17.1)
Requirement already satisfied: Send2Trash>=1.8.0 in /usr/local/lib/python3.11/dist-packages (from notebook->-r requirements.txt (line 6)) (1.8.3)
Requirement already satisfied: terminado>=0.8.3 in /usr/local/lib/python3.11/dist-packages (from notebook->-r requirements.txt (line 6)) (0.18.1)
Requirement already satisfied: prometheus-client in /usr/local/lib/python3.11/dist-packages (from notebook->-r requirements.txt (line 6)) (0.21.1)
Requirement already satisfied: nbclassic>=0.4.7 in /usr/local/lib/python3.11/dist-packages (from notebook->-r requirements.txt (line 6)) (1.2.0)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.11/dist-packages (from xgboost->-r requirements.txt (line 12)) (2.21.5)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from astunparse>=1.6.0->tensorflow->-r requirements.txt (line 1)) (0.45.1)
Requirement already satisfied: dictdiffer>=0.8.1 in /usr/local/lib/python3.11/dist-packages (from dvc-data<3.17,>=3.16.2->dvc->-r requirements.txt (line 4)) (0.9.0)
Requirement already satisfied: diskcache>=5.2.1 in /usr/local/lib/python3.11/dist-packages (from dvc-data<3.17,>=3.16.2->dvc->-r requirements.txt (line 4)) (5.6.3)
Requirement already satisfied: sqltrie<1,>=0.11.0 in /usr/local/lib/python3.11/dist-packages (from dvc-data<3.17,>=3.16.2->dvc->-r requirements.txt (line 4)) (0.11.2)
Requirement already satisfied: orjson<4,>=3 in /usr/local/lib/python3.11/dist-packages (from dvc-data<3.17,>=3.16.2->dvc->-r requirements.txt (line 4)) (3.10.16)
Requirement already satisfied: aiohttp-retry>=2.5.0 in /usr/local/lib/python3.11/dist-packages (from dvc-http>=2.29.0->dvc->-r requirements.txt (line 4)) (2.9.1)
Requirement already satisfied: billiard<5.0,>=4.2.1 in /usr/local/lib/python3.11/dist-packages (from celery->dvc->-r requirements.txt (line 4)) (4.2.1)
Requirement already satisfied: vine<6.0,>=5.1.0 in /usr/local/lib/python3.11/dist-packages (from celery->dvc->-r requirements.txt (line 4)) (5.1.0)
Requirement already satisfied: click<9.0,>=8.1.2 in /usr/local/lib/python3.11/dist-packages (from celery->dvc->-r requirements.txt (line 4)) (8.1.8)
Requirement already satisfied: click-didyoumean>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from celery->dvc->-r requirements.txt (line 4)) (0.3.1)
Requirement already satisfied: click-repl>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from celery->dvc->-r requirements.txt (line 4)) (0.3.0)
Requirement already satisfied: click-plugins>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from celery->dvc->-r requirements.txt (line 4)) (1.1.1)
Requirement already satisfied: atpublic in /usr/local/lib/python3.11/dist-packages (from flufl.lock<9,>=8.1.0->dvc->-r requirements.txt (line 4)) (5.1)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.11/dist-packages (from gto<2,>=1.6.0->dvc->-r requirements.txt (line 4)) (0.4)
Requirement already satisfied: pydantic!=2.0.0,<3,>=1.9.0 in /usr/local/lib/python3.11/dist-packages (from gto<2,>=1.6.0->dvc->-r requirements.txt (line 4)) (2.11.3)
Requirement already satisfied: semver>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from gto<2,>=1.6.0->dvc->-r requirements.txt (line 4)) (3.0.4)
Requirement already satisfied: typer>=0.4.1 in /usr/local/lib/python3.11/dist-packages (from gto<2,>=1.6.0->dvc->-r requirements.txt (line 4)) (0.15.2)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in /usr/local/lib/python3.11/dist-packages (from hydra-core>=1.1->dvc->-r requirements.txt (line 4)) (4.9.3)
Requirement already satisfied: appdirs in /usr/local/lib/python3.11/dist-packages (from iterative-telemetry>=0.0.7->dvc->-r requirements.txt (line 4)) (1.4.4)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from iterative-telemetry>=0.0.7->dvc->-r requirements.txt (line 4)) (3.18.0)
Requirement already satisfied: namex in /usr/local/lib/python3.11/dist-packages (from keras>=3.5.0->tensorflow->-r requirements.txt (line 1)) (0.0.9)
Requirement already satisfied: optree in /usr/local/lib/python3.11/dist-packages (from keras>=3.5.0->tensorflow->-r requirements.txt (line 1)) (0.15.0)
Requirement already satisfied: amqp<6.0.0,>=5.1.1 in /usr/local/lib/python3.11/dist-packages (from kombu->dvc->-r requirements.txt (line 4)) (5.3.1)
Requirement already satisfied: notebook-shim>=0.2.3 in /usr/local/lib/python3.11/dist-packages (from nbclassic>=0.4.7->notebook->-r requirements.txt (line 6)) (0.2.4)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.11/dist-packages (from nbconvert>=5->notebook->-r requirements.txt (line 6)) (4.13.4)
Requirement already satisfied: bleach!=5.0.0 in /usr/local/lib/python3.11/dist-packages (from bleach[css]!=5.0.0->nbconvert>=5->notebook->-r requirements.txt (line 6)) (6.2.0)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.11/dist-packages (from nbconvert>=5->notebook->-r requirements.txt (line 6)) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in /usr/local/lib/python3.11/dist-packages (from nbconvert>=5->notebook->-r requirements.txt (line 6)) (0.3.0)

# Thư viện

In [2]:
import pandas as pd
import numpy as np
from Mylib import myfuncs
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
import plotly.express as px
import re
import os
from plotly.subplots import make_subplots

# r1

In [ ]:
dt1 = myfuncs.load_python_object("artifacts/data_transformation/dt1_2/train_features.pkl")

pre = PolynomialFeatures(degree=3, include_bias=False)

dt1_pre = pre.fit_transform(dt1)

dt1_pre.shape

(47105, 3653)

# dc1

## Đọc dữ liệu

In [ ]:
df = myfuncs.load_python_object("artifacts/data_ingestion/train_data.pkl")

df.head()

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination,temp_bin
56032,Luxembourg,Luxembourg,49.6117,6.1300,Europe/Luxembourg,1740822300,2025-03-01 10:45,3.0,37.4,Partly cloudy,...,23.495,2,2,07:18 AM,06:18 PM,07:55 AM,08:30 PM,Waxing Crescent,1,low
34107,Sweden,Stockholm,59.3333,18.0500,Europe/Stockholm,1731056400,2024-11-08 10:00,7.3,45.1,Sunny,...,29.230,2,2,07:26 AM,03:37 PM,02:20 PM,08:48 PM,Waxing Crescent,37,low
54115,Palau,Airai,7.3575,134.5578,Pacific/Palau,1739960100,2025-02-19 19:15,27.3,81.1,Overcast,...,9.065,1,1,06:18 AM,06:13 PM,11:15 PM,10:29 AM,Waning Gibbous,69,medium
9861,South Africa,Pretoria,-25.7500,28.1900,Africa/Johannesburg,1720098900,2024-07-04 15:15,19.1,66.4,Sunny,...,13.800,1,1,06:54 AM,05:29 PM,05:33 AM,03:57 PM,Waning Crescent,5,low
65611,Macedonia,Skopje,42.0000,21.4333,Europe/Skopje,1745053200,2025-04-19 11:00,21.3,70.3,Partly Cloudy,...,13.320,1,1,05:48 AM,07:20 PM,01:04 AM,09:27 AM,Waning Gibbous,71,medium

Kich thuoc

In [ ]:
df.shape

(52542, 42)

## Ý nghĩa các cột

| Cot                       | Y nghia                                                               | Don vi | Phan loai |
| ------------------------- | --------------------------------------------------------------------- | ------ | --------- |
| **country**                     | Đất nước mà dữ liệu được đo                                     | none   | Nominal   |
| **location_name**                       | Tên thành phố                                                          | none   | Nominal   |
| **latitude**             | vĩ độ của thành phố                                                        | none   | ordinal   |
| **longitude**             | kinh độ của thành phố                                                        | none   | ordinal   |
| **timezone**             | Giờ khu vực                                                        | none   | ordinal   |
| **last_updated_epoch**            |  thời điểm cập nhật dữ liệu cuối cùng dưới dạng Unix timestamp.       | none   | ordinal   |
| **last_updated**            |  thời điểm cập nhật dữ liệu cuối cùng (local time)       | none   | ordinal   |
| **temperature_celsius**            |  nhiệt độ dưới dạng C       | none   | ordinal   |
| **temperature_fahrenheit**            |  nhiệt độ dưới dạng F      | none   | ordinal   |
| **condition_text**            |  Tình trạng thời tiết      | none   | ordinal   |
| **wind_mph**         | Tốc độ gió (mile / hour)      | none   | ordinal   |
| wind_kph         | Tốc độ gió (km / hour)      | none   | numeric   |
| wind_degree        | Hướng gió theo độ    | none   | numeric   |
| **wind_direction**         | Hướng gió chi tiết hơn     | none   | numeric   |
| **pressure_mb**         | Áp suất (milibars)    | none   | numeric   |
| pressure_in         | Áp suất (inches)    | none   | numeric   |
| **precip_mm**         | Lượng mưa (mm)    | none   | numeric   |
| **precip_in**         | Lượng mưa (inches)    | none   | numeric   |
| humidity         | Độ ẩm (%)    | none   | numeric   |
| cloud         | Phần trăm mây bao phủ (%)    | none   | numeric   |
| **feels_like_celsius**         | Nhiệt độ cơ thể cảm nhận được thay vì là thực tế    | none   | numeric   |
| **feels_like_fahrenheit**         | Nhiệt độ cơ thể cảm nhận được thay vì là thực tế    | none   | numeric   |
| visibility_km         | Tầm nhìn (km)    | none   | numeric   |
| **visibility_miles**         | Tầm nhìn (mile)    | none   | numeric   |
| uv_index         | Chỉ số tia UV    | none   | numeric   |
| **gust_mph**         | sự tăng tốc đột ngột và mạnh mẽ của gió (mile / h)    | none   | numeric   |
| gust_kph         | sự tăng tốc đột ngột và mạnh mẽ của gió (km / h)    | none   | numeric   |
| air_quality_Carbon_Monoxide         | Nồng độ $CO$    | none   | numeric   |
| air_quality_Ozone         | Nồng độ $O_3$    | none   | numeric   |
| air_quality_Nitrogen_dioxide         | Nồng độ $NO_2$    | none   | numeric   |
| air_quality_Sulphur_dioxide         | Nồng độ $SO_2$    | none   | numeric   |
| air_quality_PM2.5         | Nồng độ $PM2.5$    | none   | numeric   |
| air_quality_PM10         | Nồng độ $PM10$    | none   | numeric   |
| **air_quality_us-epa-index**         | Chỉ số AQI    | none   | numeric   |
| **air_quality_gb-defra-index**         | Chỉ số AQI    | none   | numeric   |
| sunrise         | Thời điểm mặt trời lên   | none   | ordinal   |
| sunset         | Thời điểm mặt trời lặn   | none   | ordinal   |
| moonrise         | Thời điểm trăng lên   | none   | ordinal   |
| moonset         | Thời điểm trăng lặn   | none   | ordinal   |
| moon_phase         | Pha của mặt trăng   | none   | nominal   |
| moon_illumination         | Độ sáng của mặt trăng (%)   | none   | numeric |

## Xóa các cột không cần thiết

### Xóa các cột

In [ ]:
df = df.drop(
    columns=[
        "country",
        "location_name",
        "latitude",
        "longitude",
        "timezone",
        "last_updated_epoch",
        "last_updated",
        "temperature_celsius",
        "temperature_fahrenheit",
        "condition_text",
        "wind_mph",
        "wind_direction",
        "pressure_mb",
        "precip_mm",
        "precip_in",
        "feels_like_celsius",
        "feels_like_fahrenheit",
        "visibility_miles",
        "gust_mph",
        "air_quality_us-epa-index",
        "air_quality_gb-defra-index",
    ]
)

df.columns

Index(['wind_kph', 'wind_degree', 'pressure_in', 'humidity', 'cloud',
       'visibility_km', 'uv_index', 'gust_kph', 'air_quality_Carbon_Monoxide',
       'air_quality_Ozone', 'air_quality_Nitrogen_dioxide',
       'air_quality_Sulphur_dioxide', 'air_quality_PM2.5', 'air_quality_PM10',
       'sunrise', 'sunset', 'moonrise', 'moonset', 'moon_phase',
       'moon_illumination', 'temp_bin'],
      dtype='object')

### Tỉ lệ missing các cột

In [ ]:
null_percent = df.isnull().mean() * 100
null_percent = null_percent.sort_values(ascending=False)
null_percent

wind_kph                        0.0
air_quality_Sulphur_dioxide     0.0
moon_illumination               0.0
moon_phase                      0.0
moonset                         0.0
moonrise                        0.0
sunset                          0.0
sunrise                         0.0
air_quality_PM10                0.0
air_quality_PM2.5               0.0
air_quality_Nitrogen_dioxide    0.0
wind_degree                     0.0
air_quality_Ozone               0.0
air_quality_Carbon_Monoxide     0.0
gust_kph                        0.0
uv_index                        0.0
visibility_km                   0.0
cloud                           0.0
humidity                        0.0
pressure_in                     0.0
temp_bin                        0.0
dtype: float64

### Xóa các cột có tỉ lệ missing lớn

Ti le missing của các cột đều = 0-> Khong xoa cot nao het !

In [ ]:
df.shape

(52542, 21)

## Đổi tên cột

In [ ]:
rename_dict = {
    "wind_kph": "wind_kph_num",
    "wind_degree": "wind_degree_num",
    "pressure_in": "pressure_in_num",
    "humidity": "humidity_num",
    "cloud": "cloud_num",
    "visibility_km": "visibility_km_num",
    "uv_index": "uv_index_num",
    "gust_kph": "gust_kph_num",
    "air_quality_Carbon_Monoxide": "air_quality_Carbon_Monoxide_num",
    "air_quality_Ozone": "air_quality_Ozone_num",
    "air_quality_Nitrogen_dioxide": "air_quality_Nitrogen_dioxide_num",
    "air_quality_Sulphur_dioxide": "air_quality_Sulphur_dioxide_num",
    "air_quality_PM2.5": "air_quality_PM2_5_num",
    "air_quality_PM10": "air_quality_PM10_num",
    "sunrise": "sunrise_ord",
    "sunset": "sunset_ord",
    "moonrise": "moonrise_ord",
    "moonset": "moonset_ord",
    "moon_phase": "moon_phase_nom",
    "moon_illumination": "moon_illumination_num",
    "temp_bin": "temp_bin_target",

}


df = df.rename(columns=rename_dict)

df.columns

Index(['wind_kph_num', 'wind_degree_num', 'pressure_in_num', 'humidity_num',
       'cloud_num', 'visibility_km_num', 'uv_index_num', 'gust_kph_num',
       'air_quality_Carbon_Monoxide_num', 'air_quality_Ozone_num',
       'air_quality_Nitrogen_dioxide_num', 'air_quality_Sulphur_dioxide_num',
       'air_quality_PM2_5_num', 'air_quality_PM10_num', 'sunrise_ord',
       'sunset_ord', 'moonrise_ord', 'moonset_ord', 'moon_phase_nom',
       'moon_illumination_num', 'temp_bin_target'],
      dtype='object')

## Sắp xếp các cột theo đúng thứ tự

In [ ]:
numeric_cols, numericCat_cols, cat_cols, binary_cols, nominal_cols, ordinal_cols, target_col = myfuncs.get_different_types_cols_from_df_4(df)


df = df[
    numeric_cols
    + numericCat_cols
    + binary_cols
    + nominal_cols
    + ordinal_cols
    + [target_col]
]


df.head()

,wind_kph_num,wind_degree_num,pressure_in_num,humidity_num,cloud_num,visibility_km_num,uv_index_num,gust_kph_num,air_quality_Carbon_Monoxide_num,air_quality_Ozone_num,...,air_quality_Sulphur_dioxide_num,air_quality_PM2_5_num,air_quality_PM10_num,moon_illumination_num,moon_phase_nom,sunrise_ord,sunset_ord,moonrise_ord,moonset_ord,temp_bin_target
56032,18.0,57,30.39,81,75,10.0,1.3,24.2,384.80,52.0,...,0.925,21.090,23.495,1,Waxing Crescent,07:18 AM,06:18 PM,07:55 AM,08:30 PM,low
34107,10.1,247,30.55,80,2,10.0,0.3,17.0,362.60,26.0,...,0.925,17.575,29.230,37,Waxing Crescent,07:26 AM,03:37 PM,02:20 PM,08:48 PM,low
54115,24.5,75,29.83,89,100,19.0,0.0,33.6,177.60,31.0,...,0.925,5.920,9.065,69,Waning Gibbous,06:18 AM,06:13 PM,11:15 PM,10:29 AM,medium
9861,22.3,211,30.02,12,0,10.0,6.0,25.7,240.30,76.5,...,3.500,5.700,13.800,5,Waning Crescent,06:54 AM,05:29 PM,05:33 AM,03:57 PM,low
65611,3.6,256,29.94,40,0,10.0,6.0,3.7,264.55,80.0,...,6.290,8.140,13.320,71,Waning Gibbous,05:48 AM,07:20 PM,01:04 AM,09:27 AM,medium

## Kiểm tra kiểu dữ liệu các cột

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 52542 entries, 56032 to 4001
Data columns (total 21 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   wind_kph_num                      52542 non-null  float64
 1   wind_degree_num                   52542 non-null  int64
 2   pressure_in_num                   52542 non-null  float64
 3   humidity_num                      52542 non-null  int64
 4   cloud_num                         52542 non-null  int64
 5   visibility_km_num                 52542 non-null  float64
 6   uv_index_num                      52542 non-null  float64
 7   gust_kph_num                      52542 non-null  float64
 8   air_quality_Carbon_Monoxide_num   52542 non-null  float64
 9   air_quality_Ozone_num             52542 non-null  float64
 10  air_quality_Nitrogen_dioxide_num  52542 non-null  float64
 11  air_quality_Sulphur_dioxide_num   52542 non-null  float64
 12  air_quality_PM2_5_num             52542 non-null  float64
 13  air_quality_PM10_num              52542 non-null  float64
 14  moon_illumination_num             52542 non-null  int64
 15  moon_phase_nom                    52542 non-null  object
 16  sunrise_ord                       52542 non-null  object
 17  sunset_ord                        52542 non-null  object
 18  moonrise_ord                      52542 non-null  object
 19  moonset_ord                       52542 non-null  object
 20  temp_bin_target                   52542 non-null  category
dtypes: category(1), float64(11), int64(4), object(5)
memory usage: 8.5+ MB

SAI:

- cac cot nominal, ordinal

### Chuyển kdl = kdl mong muốn + NAN

In [ ]:
for col in df.columns.tolist()[15:]:
  print(f"{col} -> {set(map(type, df[col]))}")

moon_phase_nom -> {<class 'str'>}
sunrise_ord -> {<class 'str'>}
sunset_ord -> {<class 'str'>}
moonrise_ord -> {<class 'str'>}
moonset_ord -> {<class 'str'>}
temp_bin_target -> {<class 'str'>}

- Tất cả các cột đều đúng kiểu dữ liệu

## Kiểm tra nội dung các cột `binary`

In [ ]:
for col in binary_cols:
  print(f"{col} -> {df[col].unique().tolist()}")

Không có cột nào hết

## Kiểm tra nội dung các cột `nominal`

In [ ]:
for col in nominal_cols:
    print(f"{col} -> {df[col].unique().tolist()}")

moon_phase_nom -> ['Waxing Crescent', 'Waning Gibbous', 'Waning Crescent', 'Last Quarter', 'Waxing Gibbous', 'First Quarter', 'Full Moon', 'New Moon']

## Kiểm tra nội dung các cột `ordinal`

In [ ]:
for col in ordinal_cols:
    print(f"{col} -> {df[col].unique().tolist()}")

sunrise_ord -> ['07:18 AM', '07:26 AM', '06:18 AM', '06:54 AM', '05:48 AM', '05:45 AM', '07:13 AM', '06:31 AM', '05:32 AM', '06:14 AM', '05:17 AM', '06:03 AM', '06:52 AM', '06:40 AM', '06:41 AM', '06:50 AM', '05:16 AM', '07:30 AM', '07:56 AM', '06:22 AM', '05:38 AM', '07:17 AM', '06:42 AM', '06:57 AM', '05:33 AM', '06:20 AM', '05:41 AM', '05:23 AM', '06:07 AM', '05:57 AM', '06:00 AM', '04:56 AM', '08:43 AM', '06:13 AM', '05:19 AM', '06:34 AM', '07:22 AM', '04:44 AM', '06:19 AM', '06:09 AM', '05:22 AM', '05:30 AM', '06:05 AM', '05:59 AM', '05:54 AM', '06:27 AM', '05:42 AM', '06:12 AM', '07:45 AM', '06:48 AM', '05:40 AM', '06:32 AM', '06:53 AM', '07:19 AM', '05:56 AM', '05:49 AM', '06:17 AM', '07:03 AM', '06:37 AM', '06:08 AM', '06:16 AM', '07:37 AM', '06:43 AM', '07:16 AM', '06:38 AM', '06:01 AM', '05:18 AM', '05:36 AM', '06:39 AM', '05:39 AM', '05:43 AM', '07:54 AM', '04:06 AM', '07:05 AM', '07:31 AM', '07:59 AM', '07:42 AM', '07:50 AM', '06:45 AM', '05:21 AM', '06:06 AM', '05:51 AM', '04:55 AM', '07:07 AM', '06:24 AM', '05:37 AM', '07:41 AM', '05:25 AM', '06:15 AM', '06:29 AM', '06:11 AM', '07:08 AM', '08:10 AM', '06:55 AM', '07:51 AM', '05:55 AM', '06:23 AM', '06:35 AM', '07:10 AM', '07:20 AM', '05:04 AM', '06:30 AM', '05:29 AM', '07:38 AM', '04:53 AM', '07:55 AM', '05:26 AM', '05:28 AM', '08:58 AM', '04:38 AM', '08:03 AM', '06:44 AM', '08:07 AM', '07:09 AM', '07:33 AM', '05:09 AM', '07:01 AM', '08:33 AM', '06:33 AM', '04:30 AM', '07:11 AM', '06:02 AM', '08:42 AM', '06:21 AM', '06:28 AM', '06:47 AM', '04:49 AM', '07:04 AM', '08:30 AM', '05:35 AM', '05:12 AM', '04:52 AM', '07:25 AM', '04:43 AM', '05:52 AM', '08:22 AM', '06:58 AM', '06:04 AM', '05:27 AM', '05:58 AM', '07:27 AM', '05:46 AM', '04:46 AM', '06:46 AM', '07:23 AM', '06:10 AM', '06:26 AM', '05:47 AM', '07:29 AM', '07:32 AM', '05:13 AM', '07:39 AM', '07:06 AM', '07:44 AM', '07:00 AM', '05:50 AM', '08:06 AM', '07:40 AM', '06:56 AM', '05:15 AM', '05:06 AM', '06:25 AM', '08:00 AM', '05:03 AM', '07:02 AM', '07:49 AM', '05:53 AM', '07:12 AM', '04:45 AM', '08:21 AM', '08:59 AM', '03:59 AM', '07:24 AM', '07:15 AM', '06:36 AM', '04:13 AM', '04:16 AM', '05:31 AM', '06:51 AM', '07:53 AM', '08:02 AM', '05:44 AM', '05:20 AM', '05:08 AM', '04:07 AM', '06:49 AM', '06:59 AM', '03:07 AM', '08:01 AM', '04:57 AM', '08:56 AM', '04:51 AM', '04:59 AM', '08:35 AM', '05:34 AM', '04:48 AM', '07:36 AM', '08:27 AM', '07:48 AM', '05:07 AM', '08:28 AM', '05:14 AM', '05:11 AM', '07:46 AM', '08:23 AM', '08:14 AM', '08:54 AM', '07:43 AM', '09:37 AM', '07:21 AM', '08:08 AM', '07:14 AM', '07:57 AM', '07:35 AM', '08:19 AM', '05:10 AM', '05:24 AM', '08:17 AM', '08:15 AM', '07:28 AM', '03:57 AM', '08:04 AM', '07:34 AM', '08:20 AM', '05:05 AM', '08:51 AM', '07:47 AM', '05:02 AM', '08:16 AM', '04:20 AM', '08:29 AM', '07:58 AM', '08:24 AM', '08:26 AM', '07:52 AM', '04:31 AM', '09:18 AM', '04:03 AM', '03:58 AM', '09:20 AM', '04:58 AM', '09:28 AM', '04:36 AM', '09:58 AM', '03:40 AM', '09:27 AM', '09:06 AM', '08:32 AM', '08:13 AM', '04:26 AM', '08:37 AM', '04:37 AM', '08:18 AM', '05:00 AM', '04:08 AM', '04:54 AM', '03:55 AM', '08:31 AM', '08:48 AM', '04:19 AM', '08:05 AM', '04:32 AM', '03:45 AM', '04:29 AM', '04:40 AM', '04:47 AM', '03:54 AM', '08:11 AM', '04:35 AM', '05:01 AM', '04:41 AM', '04:25 AM', '09:08 AM', '08:39 AM', '08:25 AM', '09:10 AM', '08:34 AM', '04:50 AM', '08:41 AM', '08:40 AM', '08:09 AM', '04:10 AM', '08:38 AM', '08:47 AM', '08:50 AM', '08:12 AM', '04:00 AM', '04:01 AM', '10:00 AM', '04:18 AM', '09:25 AM', '08:44 AM', '09:03 AM', '03:32 AM', '08:49 AM', '04:33 AM', '09:12 AM', '03:16 AM', '03:53 AM', '09:01 AM', '04:27 AM', '08:36 AM', '10:06 AM', '11:01 AM', '10:30 AM', '04:14 AM', '09:21 AM', '04:09 AM', '04:28 AM', '04:39 AM', '04:42 AM', '04:11 AM', '03:47 AM', '04:04 AM', '09:16 AM', '08:55 AM', '08:45 AM', '08:52 AM', '04:34 AM', '08:46 AM', '09:07 AM', '09:22 AM', '09:29 AM', '09:17 AM', '04:05 AM', '04:24 AM', '09:26 AM', '10:43 AM', '09:42 AM', '10:08 AM', '04:22 AM', '03:08 AM', '10:35 AM', '03:51 AM', '09:05 AM', '03:15 AM', '03:48 AM', '09:15 AM', '03:09 AM', '09:00 AM', '04:21 AM', '09:23 AM', '04:23 AM', '03:28 AM', '04:12 AM', '08:57 AM', '09:02 AM', '03:42 AM', '03:49 AM', '10:22 AM', '03:50 AM', '10:42 AM', '03:23 AM', '10:29 AM', '10:50 AM', '04:02 AM', '10:55 AM', '09:19 AM', '03:37 AM', '03:33 AM', '09:11 AM', '10:25 AM', '09:13 AM', '11:04 AM', '11:03 AM', '04:17 AM', '10:54 AM', '09:51 AM', '03:14 AM', '09:31 AM', '03:29 AM', '03:05 AM', '10:44 AM', '03:46 AM', '04:15 AM', '03:27 AM', '10:17 AM', '09:24 AM', '10:45 AM', '03:31 AM', '09:52 AM', '03:26 AM', '09:34 AM', '03:56 AM', '08:53 AM', '10:56 AM', '03:12 AM', '10:52 AM', '03:36 AM', '09:55 AM', '03:44 AM', '09:09 AM', '10:48 AM', '09:43 AM', '03:34 AM', '03:19 AM', '10:53 AM', '09:48 AM', '09:35 AM', '10:19 AM', '10:57 AM', '02:58 AM', '10:34 AM', '03:39 AM', '10:59 AM', '09:38 AM', '02:55 AM', '10:27 AM', '10:02 AM', '02:48 AM', '03:41 AM', '10:28 AM', '11:00 AM', '03:06 AM', '09:40 AM', '10:58 AM', '11:02 AM', '10:11 AM', '10:32 AM', '03:38 AM', '03:52 AM', '09:04 AM', '03:43 AM', '09:14 AM', '03:30 AM', '03:25 AM', '10:33 AM', '02:57 AM', '03:21 AM', '09:49 AM', '10:38 AM', '10:46 AM', '03:20 AM', '03:35 AM', '03:11 AM', '10:40 AM', '10:24 AM', '02:49 AM', '02:53 AM', '03:13 AM', '10:14 AM', '10:36 AM', '03:10 AM', '03:18 AM']
sunset_ord -> ['06:18 PM', '03:37 PM', '06:13 PM', '05:29 PM', '07:20 PM', '06:17 PM', '04:01 PM', '07:11 PM', '06:52 PM', '05:57 PM', '05:44 PM', '06:09 PM', '04:39 PM', '05:09 PM', '05:21 PM', '06:53 PM', '05:48 PM', '06:19 PM', '04:00 PM', '06:40 PM', '05:50 PM', '07:01 PM', '05:36 PM', '07:18 PM', '06:27 PM', '06:16 PM', '05:22 PM', '07:19 PM', '06:10 PM', '05:46 PM', '06:28 PM', '06:01 PM', '05:53 PM', '06:26 PM', '04:55 PM', '06:44 PM', '06:20 PM', '06:21 PM', '06:46 PM', '05:35 PM', '08:40 PM', '06:03 PM', '06:24 PM', '06:23 PM', '08:14 PM', '05:11 PM', '06:35 PM', '05:34 PM', '05:59 PM', '06:11 PM', '05:27 PM', '05:37 PM', '06:55 PM', '06:57 PM', '04:02 PM', '07:58 PM', '08:54 PM', '09:30 PM', '06:41 PM', '06:37 PM', '05:20 PM', '05:56 PM', '08:53 PM', '07:21 PM', '06:31 PM', '04:54 PM', '05:03 PM', '05:55 PM', '04:26 PM', '06:48 PM', '05:49 PM', '06:25 PM', '10:06 PM', '08:25 PM', '05:40 PM', '06:08 PM', '07:27 PM', '09:18 PM', '06:56 PM', '04:13 PM', '08:32 PM', '09:04 PM', '05:13 PM', '06:12 PM', '06:15 PM', '05:42 PM', '08:22 PM', '04:03 PM', '06:29 PM', '08:49 PM', '06:02 PM', '04:41 PM', '05:17 PM', '07:00 PM', '04:36 PM', '08:21 PM', '06:32 PM', '08:47 PM', '06:59 PM', '05:07 PM', '04:47 PM', '07:45 PM', '07:14 PM', '09:27 PM', '07:10 PM', '05:08 PM', '07:03 PM', '06:07 PM', '05:18 PM', '10:05 PM', '06:22 PM', '07:07 PM', '07:15 PM', '06:30 PM', '07:05 PM', '07:23 PM', '03:43 PM', '09:41 PM', '05:32 PM', '06:00 PM', '05:00 PM', '06:39 PM', '05:12 PM', '10:22 PM', '04:31 PM', '07:57 PM', '05:10 PM', '05:52 PM', '05:51 PM', '06:45 PM', '08:43 PM', '05:25 PM', '08:41 PM', '04:30 PM', '07:35 PM', '06:51 PM', '05:28 PM', '07:09 PM', '05:26 PM', '06:47 PM', '09:13 PM', '07:17 PM', '07:38 PM', '05:58 PM', '05:47 PM', '07:06 PM', '04:56 PM', '08:04 PM', '08:15 PM', '04:17 PM', '09:22 PM', '04:40 PM', '08:48 PM', '05:19 PM', '08:01 PM', '08:35 PM', '04:15 PM', '06:14 PM', '06:58 PM', '07:41 PM', '08:17 PM', '05:33 PM', '07:16 PM', '05:38 PM', '07:12 PM', '05:54 PM', '06:05 PM', '06:38 PM', '09:34 PM', '06:34 PM', '09:02 PM', '08:11 PM', '09:58 PM', '03:58 PM', '06:49 PM', '05:39 PM', '07:29 PM', '04:44 PM', '06:04 PM', '06:06 PM', '07:30 PM', '04:58 PM', '08:19 PM', '08:12 PM', '04:38 PM', '07:04 PM', '05:31 PM', '05:43 PM', '05:45 PM', '08:31 PM', '09:46 PM', '08:34 PM', '04:20 PM', '07:39 PM', '06:33 PM', '03:32 PM', '07:25 PM', '04:29 PM', '05:01 PM', '08:51 PM', '05:14 PM', '08:00 PM', '07:13 PM', '06:50 PM', '06:43 PM', '04:06 PM', '08:28 PM', '07:22 PM', '10:30 PM', '08:57 PM', '07:44 PM', '10:27 PM', '04:49 PM', '08:29 PM', '07:54 PM', '07:53 PM', '08:42 PM', '05:23 PM', '06:36 PM', '06:54 PM', '08:09 PM', '06:42 PM', '07:37 PM', '08:44 PM', '09:52 PM', '04:34 PM', '08:33 PM', '11:40 PM', '08:03 PM', '07:02 PM', '05:41 PM', '08:45 PM', '03:31 PM', '09:25 PM', '04:46 PM', '05:06 PM', '04:21 PM', '07:51 PM', '07:26 PM', '07:24 PM', '04:52 PM', '05:30 PM', '09:15 PM', '07:36 PM', '03:56 PM', '05:04 PM', '08:05 PM', '04:59 PM', '05:24 PM', '08:23 PM', '08:07 PM', '08:24 PM', '07:56 PM', '07:47 PM', '07:32 PM', '07:08 PM', '03:10 PM', '04:51 PM', '04:11 PM', '08:27 PM', '03:35 PM', '08:26 PM', '07:34 PM', '09:35 PM', '10:04 PM', '07:59 PM', '09:28 PM', '09:45 PM', '09:43 PM', '09:19 PM', '10:00 PM', '04:18 PM', '08:10 PM', '08:37 PM', '04:57 PM', '10:36 PM', '07:43 PM', '05:15 PM', '04:16 PM', '08:52 PM', '04:33 PM', '09:32 PM', '04:09 PM', '09:05 PM', '04:50 PM', '08:38 PM', '10:02 PM', '05:16 PM', '07:42 PM', '08:02 PM', '08:16 PM', '05:02 PM', '07:50 PM', '04:48 PM', '04:37 PM', '04:35 PM', '05:05 PM', '10:42 PM', '09:49 PM', '04:53 PM', '04:12 PM', '04:19 PM', '04:14 PM', '07:28 PM', '09:31 PM', '04:42 PM', '07:52 PM', '03:16 PM', '09:00 PM', '08:20 PM', '04:05 PM', '10:03 PM', '10:07 PM', '08:18 PM', '08:08 PM', '07:33 PM', '04:45 PM', '10:41 PM', '04:23 PM', '08:56 PM', '08:39 PM', '09:24 PM', '09:11 PM', '10:13 PM', '11:07 PM', '07:49 PM', '09:57 PM', '09:55 PM', '08:50 PM', '07:31 PM', '03:18 PM', '04:10 PM', '09:39 PM', '09:48 PM', '09:09 PM', '10:48 PM', '04:32 PM', '04:22 PM', '07:48 PM', '08:13 PM', '09:40 PM', '07:55 PM', '09:36 PM', '09:20 PM', '07:46 PM', '03:57 PM', '03:45 PM', '03:53 PM', '08:55 PM', '03:11 PM', '09:06 PM', '04:27 PM', '04:04 PM', '08:30 PM', '03:12 PM', '09:50 PM', '09:16 PM', '08:58 PM', '03:54 PM', '04:07 PM', '10:21 PM', '09:38 PM', '09:29 PM', '03:51 PM', '09:14 PM', '04:28 PM', '03:52 PM', '03:01 PM', '02:52 PM', '09:08 PM', '09:47 PM', '07:40 PM', '09:01 PM', '09:23 PM', '04:43 PM', '09:10 PM', '03:14 PM', '10:08 PM', '03:25 PM', '10:40 PM', '11:33 PM', '10:59 PM', '03:23 PM', '02:47 PM', '03:49 PM', '08:59 PM', '09:53 PM', '03:55 PM', '03:26 PM', '03:38 PM', '03:33 PM', '03:42 PM', '10:11 PM', '10:12 PM', '09:33 PM', '08:06 PM', '03:41 PM', '10:32 PM', '11:09 PM', '03:59 PM', '03:05 PM', '10:43 PM', '09:21 PM', '03:39 PM', '09:44 PM', '09:54 PM', '11:12 PM', '03:30 PM', '04:25 PM', '03:46 PM', '08:36 PM', '09:26 PM', '04:24 PM', '02:54 PM', '03:44 PM', '03:48 PM', '08:46 PM', '02:50 PM', '10:39 PM', '03:24 PM', '09:07 PM', '02:51 PM', '10:46 PM', '10:01 PM', '09:17 PM', '10:19 PM', '10:16 PM', '04:08 PM', '03:29 PM', '03:36 PM', '03:28 PM', '09:37 PM', '09:56 PM', '03:40 PM', '03:47 PM', '03:20 PM', '10:50 PM', '09:12 PM', '10:28 PM', '09:03 PM', '09:51 PM', '11:39 PM', '09:59 PM', '03:22 PM', '10:31 PM', '10:20 PM', '11:45 PM', '03:21 PM', '09:42 PM', '11:52 PM', '03:13 PM', '10:29 PM', '11:23 PM', '03:27 PM', '10:18 PM', '03:34 PM', '10:44 PM', '11:15 PM', '10:47 PM', '11:02 PM', '02:56 PM', '10:15 PM', '11:36 PM', '10:10 PM', '02:53 PM', '10:17 PM', '03:15 PM', '10:33 PM', '11:34 PM', '11:29 PM', '11:57 PM', '11:10 PM', '10:09 PM', '11:03 PM', '11:54 PM', '10:37 PM', '02:58 PM', '10:49 PM', '02:48 PM', '03:50 PM', '11:31 PM', '03:19 PM', '11:25 PM', '03:04 PM', '10:45 PM', '10:35 PM', '02:49 PM', '11:49 PM', '10:26 PM', '03:17 PM', '02:57 PM', '10:34 PM', '11:41 PM', '10:38 PM', '02:59 PM', '11:18 PM', '11:26 PM', '10:25 PM', '10:23 PM', '11:38 PM', '03:07 PM', '11:55 PM', '11:58 PM', '10:56 PM', '10:24 PM', '11:21 PM', '11:06 PM', '12:03 AM', '10:51 PM', '10:57 PM', '03:08 PM', '11:27 PM', '11:19 PM', '03:02 PM', '11:20 PM', '11:53 PM', '11:30 PM', '11:14 PM', '11:28 PM', '11:50 PM', '02:55 PM', '11:35 PM', '10:54 PM', '10:53 PM', '11:37 PM', '11:32 PM']

### Biển đổi 4 cột sunrise_ord, sunset_ord, moonrise_ord, moonset_ord

Chuyển các giá trị từ dạng giờ:phút sang dạng khoảng thời gian

VD: 07:03 AM -> 7 - 8 (khoảng thời gian từ 7 - 8h)

In [ ]:
format = r"\d+:\d+\s*(AM|PM)"

df_ordinal_cols = df[ordinal_cols]
df_ordinal_cols.head()

      sunrise_ord sunset_ord moonrise_ord moonset_ord
56032    07:18 AM   06:18 PM     07:55 AM    08:30 PM
34107    07:26 AM   03:37 PM     02:20 PM    08:48 PM
54115    06:18 AM   06:13 PM     11:15 PM    10:29 AM
9861     06:54 AM   05:29 PM     05:33 AM    03:57 PM
65611    05:48 AM   07:20 PM     01:04 AM    09:27 AM

In [ ]:
index_not_satisfy_format = df_ordinal_cols[df_ordinal_cols.applymap(lambda item: re.fullmatch(format, item) is None)].stack().index
index_not_satisfy_format

<ipython-input-17-c8ef9647d5b6>:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  index_not_satisfy_format = df_ordinal_cols[df_ordinal_cols.applymap(lambda item: re.fullmatch(format, item) is None)].stack().index

MultiIndex([(36985, 'moonrise_ord'),
            (25501, 'moonrise_ord'),
            (62647,  'moonset_ord'),
            (39776,  'moonset_ord'),
            (31084, 'moonrise_ord'),
            (54355, 'moonrise_ord'),
            (45475,  'moonset_ord'),
            (45510,  'moonset_ord'),
            (36978, 'moonrise_ord'),
            (25389, 'moonrise_ord'),
            ...
            (40035,  'moonset_ord'),
            (56577,  'moonset_ord'),
            ( 5901,  'moonset_ord'),
            (42614, 'moonrise_ord'),
            (62582,  'moonset_ord'),
            (36758, 'moonrise_ord'),
            (62759,  'moonset_ord'),
            (23073,  'moonset_ord'),
            ( 2967, 'moonrise_ord'),
            (51300,  'moonset_ord')],
           length=3512)

In [ ]:
df_ordinal_cols.stack()[index_not_satisfy_format].unique()

array(['No moonrise', 'No moonset'], dtype=object)

In [ ]:
# Get các giá trị ứng với hiện tượng có xảy ra
df_ordinal_cols_happen_stack = df_ordinal_cols.stack()
df_ordinal_cols_happen_stack = df_ordinal_cols_happen_stack[~df_ordinal_cols_happen_stack.index.isin(index_not_satisfy_format)]
len(df_ordinal_cols_happen_stack)

206656

In [ ]:
# Chuỗi nào có PM thì giá trị giờ cộng thêm 12 phút
def process_time(gold_time: str):
  if gold_time.endswith("PM"):
    parts = gold_time.split(":")
    hour = int(parts[0]) + 12
    gold_time = f"{hour}:{parts[1]}"

  res = re.split("(AM|PM)", gold_time)[0].strip()
  res = res.split(":")[0]
  return res

df_ordinal_cols_happen_stack = df_ordinal_cols_happen_stack.apply(lambda item: process_time(item))
df_ordinal_cols_happen_stack.unique()

array(['07', '18', '20', '15', '14', '06', '23', '10', '17', '05', '19',
       '01', '09', '16', '11', '03', '08', '24', '12', '22', '21', '02',
       '13', '04'], dtype=object)

In [ ]:
# Cập nhật
df_ordinal_cols_stack = df_ordinal_cols.stack()
df_ordinal_cols_stack[df_ordinal_cols_happen_stack.index] = df_ordinal_cols_happen_stack

df_ordinal_cols_stack.unstack()

      sunrise_ord sunset_ord moonrise_ord moonset_ord
56032          07         18           07          20
34107          07         15           14          20
54115          06         18           23          10
9861           06         17           05          15
65611          05         19           01          09
...           ...        ...          ...         ...
19337          06         18           22          09
4582           05         18           06          19
23724          06         19           18          05
11085          06         17           10          23
4001           05         20           03          18

[52542 rows x 4 columns]

In [ ]:
df[ordinal_cols] = df_ordinal_cols_stack.unstack()

df['moonrise_ord'].unique()

array(['07', '14', '23', '05', '01', '18', '20', '03', '08', '24',
       'No moonrise', '22', '21', '16', '11', '10', '09', '12', '04',
       '02', '06', '19', '13', '17', '15'], dtype=object)

## Kiểm tra nội dung các cột `target`

In [ ]:
print(f"{target_col} -> {df[target_col].unique().tolist()}")

temp_bin_target -> ['low', 'medium', 'high']

## Fill missing value

In [ ]:
preprocessor = ColumnTransformer(
    transformers=[
        ("num", SimpleImputer(strategy="mean"), numeric_cols),
        ("numCat", SimpleImputer(strategy="most_frequent"), numericCat_cols),
        ("cat", SimpleImputer(strategy="most_frequent"), cat_cols),
        ("target", SimpleImputer(strategy="most_frequent"), [target_col]),
    ]
)

df = preprocessor.fit_transform(df)

df = pd.DataFrame(
    df, columns=numeric_cols + numericCat_cols + cat_cols + [target_col]
)

df.head()

,wind_kph_num,wind_degree_num,pressure_in_num,humidity_num,cloud_num,visibility_km_num,uv_index_num,gust_kph_num,air_quality_Carbon_Monoxide_num,air_quality_Ozone_num,...,air_quality_Sulphur_dioxide_num,air_quality_PM2_5_num,air_quality_PM10_num,moon_illumination_num,moon_phase_nom,sunrise_ord,sunset_ord,moonrise_ord,moonset_ord,temp_bin_target
0,18.0,57.0,30.39,81.0,75.0,10.0,1.3,24.2,384.8,52.0,...,0.925,21.09,23.495,1.0,Waxing Crescent,07,18,07,20,low
1,10.1,247.0,30.55,80.0,2.0,10.0,0.3,17.0,362.6,26.0,...,0.925,17.575,29.23,37.0,Waxing Crescent,07,15,14,20,low
2,24.5,75.0,29.83,89.0,100.0,19.0,0.0,33.6,177.6,31.0,...,0.925,5.92,9.065,69.0,Waning Gibbous,06,18,23,10,medium
3,22.3,211.0,30.02,12.0,0.0,10.0,6.0,25.7,240.3,76.5,...,3.5,5.7,13.8,5.0,Waning Crescent,06,17,05,15,low
4,3.6,256.0,29.94,40.0,0.0,10.0,6.0,3.7,264.55,80.0,...,6.29,8.14,13.32,71.0,Waning Gibbous,05,19,01,09,medium

In [ ]:
np.all(df.isnull().sum() == 0)

True

## Chuyển đổi các cột về đúng kiểu dữ liệu

In [ ]:
df[numeric_cols] = df[numeric_cols].astype("float32")
df[numericCat_cols] = df[numericCat_cols].astype("float32")
df[cat_cols] = df[cat_cols].astype("category")
df[target_col] = df[target_col].astype("category")

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52542 entries, 0 to 52541
Data columns (total 21 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   wind_kph_num                      52542 non-null  float32
 1   wind_degree_num                   52542 non-null  float32
 2   pressure_in_num                   52542 non-null  float32
 3   humidity_num                      52542 non-null  float32
 4   cloud_num                         52542 non-null  float32
 5   visibility_km_num                 52542 non-null  float32
 6   uv_index_num                      52542 non-null  float32
 7   gust_kph_num                      52542 non-null  float32
 8   air_quality_Carbon_Monoxide_num   52542 non-null  float32
 9   air_quality_Ozone_num             52542 non-null  float32
 10  air_quality_Nitrogen_dioxide_num  52542 non-null  float32
 11  air_quality_Sulphur_dioxide_num   52542 non-null  float32
 12  air_quality_PM2_5_num             52542 non-null  float32
 13  air_quality_PM10_num              52542 non-null  float32
 14  moon_illumination_num             52542 non-null  float32
 15  moon_phase_nom                    52542 non-null  category
 16  sunrise_ord                       52542 non-null  category
 17  sunset_ord                        52542 non-null  category
 18  moonrise_ord                      52542 non-null  category
 19  moonset_ord                       52542 non-null  category
 20  temp_bin_target                   52542 non-null  category
dtypes: category(6), float32(15)
memory usage: 3.3 MB

## Loại bỏ duplicates

In [ ]:
print(f"Tỉ lệ duplicates: {len(df.index[df.duplicated()]) / len(df.index) * 100}")
df = df.drop_duplicates().reset_index(drop=True)

True

## Chuẩn bị thứ tự cho các cột `ordinal`, `binary`

In [ ]:
ordinal_cols

NameError: name 'ordinal_cols' is not defined

In [ ]:
a = df['moonset_ord'].unique().tolist()
a

['20',
 '10',
 '15',
 '09',
 '11',
 '05',
 '07',
 '16',
 '12',
 '24',
 '08',
 '22',
 '02',
 '23',
 '13',
 '03',
 '01',
 '06',
 '17',
 '19',
 '21',
 '04',
 '18',
 'No moonset',
 '14']

In [ ]:
FEATURE_ORDINAL_DICT = {
    "sunrise_ord": ["02", "03", "04", "05", "06", "07", "08", "09", "10", "11"],
    "sunset_ord": ['12', '14','15', '16', '17', '18',  '19',  '20', '21', '22', '23' ],
    "moonrise_ord": [
        "No moonrise",
        "01",
        "02",
        "03",
        "04",
        "05",
        "06",
        "07",
        "08",
        "09",
        "10",
        "11",
        "12",
        "13",
        "14",
        "15",
        "16",
        "17",
        "18",
        "19",
        "20",
        "21",
        "22",
        "23",
        "24",
    ],
    "moonset_ord": [
        'No moonset',
        "01",
        "02",
        "03",
        "04",
        "05",
        "06",
        "07",
        "08",
        "09",
        "10",
        "11",
        "12",
        "13",
        "14",
        "15",
        "16",
        "17",
        "18",
        "19",
        "20",
        "21",
        "22",
        "23",
        "24",
    ],
}

# dc2

## Đọc dữ liệu

In [ ]:
df = myfuncs.load_python_object("artifacts/data_ingestion/train_data.pkl")

df.head()

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination,temp_bin
56032,Luxembourg,Luxembourg,49.6117,6.1300,Europe/Luxembourg,1740822300,2025-03-01 10:45,3.0,37.4,Partly cloudy,...,23.495,2,2,07:18 AM,06:18 PM,07:55 AM,08:30 PM,Waxing Crescent,1,low
34107,Sweden,Stockholm,59.3333,18.0500,Europe/Stockholm,1731056400,2024-11-08 10:00,7.3,45.1,Sunny,...,29.230,2,2,07:26 AM,03:37 PM,02:20 PM,08:48 PM,Waxing Crescent,37,low
54115,Palau,Airai,7.3575,134.5578,Pacific/Palau,1739960100,2025-02-19 19:15,27.3,81.1,Overcast,...,9.065,1,1,06:18 AM,06:13 PM,11:15 PM,10:29 AM,Waning Gibbous,69,medium
9861,South Africa,Pretoria,-25.7500,28.1900,Africa/Johannesburg,1720098900,2024-07-04 15:15,19.1,66.4,Sunny,...,13.800,1,1,06:54 AM,05:29 PM,05:33 AM,03:57 PM,Waning Crescent,5,low
65611,Macedonia,Skopje,42.0000,21.4333,Europe/Skopje,1745053200,2025-04-19 11:00,21.3,70.3,Partly Cloudy,...,13.320,1,1,05:48 AM,07:20 PM,01:04 AM,09:27 AM,Waning Gibbous,71,medium

Kich thuoc

In [ ]:
df.shape

(52542, 42)

## Ý nghĩa các cột

| Cot                       | Y nghia                                                               | Don vi | Phan loai |
| ------------------------- | --------------------------------------------------------------------- | ------ | --------- |
| **country**                     | Đất nước mà dữ liệu được đo                                     | none   | Nominal   |
| **location_name**                       | Tên thành phố                                                          | none   | Nominal   |
| **latitude**             | vĩ độ của thành phố                                                        | none   | ordinal   |
| **longitude**             | kinh độ của thành phố                                                        | none   | ordinal   |
| **timezone**             | Giờ khu vực                                                        | none   | ordinal   |
| **last_updated_epoch**            |  thời điểm cập nhật dữ liệu cuối cùng dưới dạng Unix timestamp.       | none   | ordinal   |
| **last_updated**            |  thời điểm cập nhật dữ liệu cuối cùng (local time)       | none   | ordinal   |
| **temperature_celsius**            |  nhiệt độ dưới dạng C       | none   | ordinal   |
| **temperature_fahrenheit**            |  nhiệt độ dưới dạng F      | none   | ordinal   |
| **condition_text**            |  Tình trạng thời tiết      | none   | ordinal   |
| **wind_mph**         | Tốc độ gió (mile / hour)      | none   | ordinal   |
| wind_kph         | Tốc độ gió (km / hour)      | none   | numeric   |
| wind_degree        | Hướng gió theo độ    | none   | numeric   |
| **wind_direction**         | Hướng gió chi tiết hơn     | none   | numeric   |
| **pressure_mb**         | Áp suất (milibars)    | none   | numeric   |
| pressure_in         | Áp suất (inches)    | none   | numeric   |
| **precip_mm**         | Lượng mưa (mm)    | none   | numeric   |
| **precip_in**         | Lượng mưa (inches)    | none   | numeric   |
| humidity         | Độ ẩm (%)    | none   | numeric   |
| cloud         | Phần trăm mây bao phủ (%)    | none   | numeric   |
| **feels_like_celsius**         | Nhiệt độ cơ thể cảm nhận được thay vì là thực tế    | none   | numeric   |
| **feels_like_fahrenheit**         | Nhiệt độ cơ thể cảm nhận được thay vì là thực tế    | none   | numeric   |
| visibility_km         | Tầm nhìn (km)    | none   | numeric   |
| **visibility_miles**         | Tầm nhìn (mile)    | none   | numeric   |
| uv_index         | Chỉ số tia UV    | none   | numeric   |
| **gust_mph**         | sự tăng tốc đột ngột và mạnh mẽ của gió (mile / h)    | none   | numeric   |
| gust_kph         | sự tăng tốc đột ngột và mạnh mẽ của gió (km / h)    | none   | numeric   |
| air_quality_Carbon_Monoxide         | Nồng độ $CO$    | none   | numeric   |
| air_quality_Ozone         | Nồng độ $O_3$    | none   | numeric   |
| air_quality_Nitrogen_dioxide         | Nồng độ $NO_2$    | none   | numeric   |
| air_quality_Sulphur_dioxide         | Nồng độ $SO_2$    | none   | numeric   |
| air_quality_PM2.5         | Nồng độ $PM2.5$    | none   | numeric   |
| air_quality_PM10         | Nồng độ $PM10$    | none   | numeric   |
| **air_quality_us-epa-index**         | Chỉ số AQI    | none   | numeric   |
| **air_quality_gb-defra-index**         | Chỉ số AQI    | none   | numeric   |
| sunrise         | Thời điểm mặt trời lên   | none   | ordinal   |
| sunset         | Thời điểm mặt trời lặn   | none   | ordinal   |
| moonrise         | Thời điểm trăng lên   | none   | ordinal   |
| moonset         | Thời điểm trăng lặn   | none   | ordinal   |
| moon_phase         | Pha của mặt trăng   | none   | nominal   |
| moon_illumination         | Độ sáng của mặt trăng (%)   | none   | numeric |

## Xóa các cột không cần thiết

### Xóa các cột

In [ ]:
df.columns

Index(['country', 'location_name', 'latitude', 'longitude', 'timezone',
       'last_updated_epoch', 'last_updated', 'temperature_celsius',
       'temperature_fahrenheit', 'condition_text', 'wind_mph', 'wind_kph',
       'wind_degree', 'wind_direction', 'pressure_mb', 'pressure_in',
       'precip_mm', 'precip_in', 'humidity', 'cloud', 'feels_like_celsius',
       'feels_like_fahrenheit', 'visibility_km', 'visibility_miles',
       'uv_index', 'gust_mph', 'gust_kph', 'air_quality_Carbon_Monoxide',
       'air_quality_Ozone', 'air_quality_Nitrogen_dioxide',
       'air_quality_Sulphur_dioxide', 'air_quality_PM2.5', 'air_quality_PM10',
       'air_quality_us-epa-index', 'air_quality_gb-defra-index', 'sunrise',
       'sunset', 'moonrise', 'moonset', 'moon_phase', 'moon_illumination',
       'temp_bin'],
      dtype='object')

In [ ]:
df = df.drop(
    columns=[
        "country",
        "location_name",
        "latitude",
        "longitude",
        "timezone",
        "last_updated_epoch",
        "last_updated",
        "temperature_celsius",
        "temperature_fahrenheit",
        "condition_text",
        "wind_mph",
        "wind_direction",
        "pressure_mb",
        "precip_mm",
        "precip_in",
        "feels_like_celsius",
        "feels_like_fahrenheit",
        "visibility_miles",
        "gust_mph",
        "air_quality_us-epa-index",
        "air_quality_gb-defra-index",
        'sunrise',
        'sunset',
        'moonrise',
        'moonset'
    ]
)

df.columns

Index(['wind_kph', 'wind_degree', 'pressure_in', 'humidity', 'cloud',
       'visibility_km', 'uv_index', 'gust_kph', 'air_quality_Carbon_Monoxide',
       'air_quality_Ozone', 'air_quality_Nitrogen_dioxide',
       'air_quality_Sulphur_dioxide', 'air_quality_PM2.5', 'air_quality_PM10',
       'moon_phase', 'moon_illumination', 'temp_bin'],
      dtype='object')

### Tỉ lệ missing các cột

In [ ]:
null_percent = df.isnull().mean() * 100
null_percent = null_percent.sort_values(ascending=False)
null_percent

wind_kph                        0.0
air_quality_Ozone               0.0
moon_illumination               0.0
moon_phase                      0.0
air_quality_PM10                0.0
air_quality_PM2.5               0.0
air_quality_Sulphur_dioxide     0.0
air_quality_Nitrogen_dioxide    0.0
air_quality_Carbon_Monoxide     0.0
wind_degree                     0.0
gust_kph                        0.0
uv_index                        0.0
visibility_km                   0.0
cloud                           0.0
humidity                        0.0
pressure_in                     0.0
temp_bin                        0.0
dtype: float64

### Xóa các cột có tỉ lệ missing lớn

Ti le missing của các cột đều = 0-> Khong xoa cot nao het !

In [ ]:
df.shape

(52542, 21)

## Đổi tên cột

In [ ]:
rename_dict = {
    "wind_kph": "wind_kph_num",
    "wind_degree": "wind_degree_num",
    "pressure_in": "pressure_in_num",
    "humidity": "humidity_num",
    "cloud": "cloud_num",
    "visibility_km": "visibility_km_num",
    "uv_index": "uv_index_num",
    "gust_kph": "gust_kph_num",
    "air_quality_Carbon_Monoxide": "air_quality_Carbon_Monoxide_num",
    "air_quality_Ozone": "air_quality_Ozone_num",
    "air_quality_Nitrogen_dioxide": "air_quality_Nitrogen_dioxide_num",
    "air_quality_Sulphur_dioxide": "air_quality_Sulphur_dioxide_num",
    "air_quality_PM2.5": "air_quality_PM2_5_num",
    "air_quality_PM10": "air_quality_PM10_num",
    "moon_phase": "moon_phase_nom",
    "moon_illumination": "moon_illumination_num",
    "temp_bin": "temp_bin_target",

}


df = df.rename(columns=rename_dict)

df.columns

Index(['wind_kph_num', 'wind_degree_num', 'pressure_in_num', 'humidity_num',
       'cloud_num', 'visibility_km_num', 'uv_index_num', 'gust_kph_num',
       'air_quality_Carbon_Monoxide_num', 'air_quality_Ozone_num',
       'air_quality_Nitrogen_dioxide_num', 'air_quality_Sulphur_dioxide_num',
       'air_quality_PM2_5_num', 'air_quality_PM10_num', 'moon_phase_nom',
       'moon_illumination_num', 'temp_bin_target'],
      dtype='object')

## Sắp xếp các cột theo đúng thứ tự

In [ ]:
numeric_cols, numericCat_cols, cat_cols, binary_cols, nominal_cols, ordinal_cols, target_col = myfuncs.get_different_types_cols_from_df_4(df)


df = df[
    numeric_cols
    + numericCat_cols
    + binary_cols
    + nominal_cols
    + ordinal_cols
    + [target_col]
]


df.head()

,wind_kph_num,wind_degree_num,pressure_in_num,humidity_num,cloud_num,visibility_km_num,uv_index_num,gust_kph_num,air_quality_Carbon_Monoxide_num,air_quality_Ozone_num,air_quality_Nitrogen_dioxide_num,air_quality_Sulphur_dioxide_num,air_quality_PM2_5_num,air_quality_PM10_num,moon_illumination_num,moon_phase_nom,temp_bin_target
56032,18.0,57,30.39,81,75,10.0,1.3,24.2,384.80,52.0,17.205,0.925,21.090,23.495,1,Waxing Crescent,low
34107,10.1,247,30.55,80,2,10.0,0.3,17.0,362.60,26.0,31.820,0.925,17.575,29.230,37,Waxing Crescent,low
54115,24.5,75,29.83,89,100,19.0,0.0,33.6,177.60,31.0,0.925,0.925,5.920,9.065,69,Waning Gibbous,medium
9861,22.3,211,30.02,12,0,10.0,6.0,25.7,240.30,76.5,1.100,3.500,5.700,13.800,5,Waning Crescent,low
65611,3.6,256,29.94,40,0,10.0,6.0,3.7,264.55,80.0,8.695,6.290,8.140,13.320,71,Waning Gibbous,medium

## Kiểm tra kiểu dữ liệu các cột

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 52542 entries, 56032 to 4001
Data columns (total 17 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   wind_kph_num                      52542 non-null  float64
 1   wind_degree_num                   52542 non-null  int64
 2   pressure_in_num                   52542 non-null  float64
 3   humidity_num                      52542 non-null  int64
 4   cloud_num                         52542 non-null  int64
 5   visibility_km_num                 52542 non-null  float64
 6   uv_index_num                      52542 non-null  float64
 7   gust_kph_num                      52542 non-null  float64
 8   air_quality_Carbon_Monoxide_num   52542 non-null  float64
 9   air_quality_Ozone_num             52542 non-null  float64
 10  air_quality_Nitrogen_dioxide_num  52542 non-null  float64
 11  air_quality_Sulphur_dioxide_num   52542 non-null  float64
 12  air_quality_PM2_5_num             52542 non-null  float64
 13  air_quality_PM10_num              52542 non-null  float64
 14  moon_illumination_num             52542 non-null  int64
 15  moon_phase_nom                    52542 non-null  object
 16  temp_bin_target                   52542 non-null  category
dtypes: category(1), float64(11), int64(4), object(1)
memory usage: 6.9+ MB

SAI:

- cac cot nominal, ordinal

### Chuyển kdl = kdl mong muốn + NAN

In [ ]:
for col in df.columns.tolist()[15:]:
  print(f"{col} -> {set(map(type, df[col]))}")

moon_phase_nom -> {<class 'str'>}
temp_bin_target -> {<class 'str'>}

- Tất cả các cột đều đúng kiểu dữ liệu

## Kiểm tra nội dung các cột `binary`

In [ ]:
for col in binary_cols:
  print(f"{col} -> {df[col].unique().tolist()}")

Không có cột nào hết

## Kiểm tra nội dung các cột `nominal`

In [ ]:
for col in nominal_cols:
    print(f"{col} -> {df[col].unique().tolist()}")

moon_phase_nom -> ['Waxing Crescent', 'Waning Gibbous', 'Waning Crescent', 'Last Quarter', 'Waxing Gibbous', 'First Quarter', 'Full Moon', 'New Moon']

## Kiểm tra nội dung các cột `ordinal`

In [ ]:
for col in ordinal_cols:
    print(f"{col} -> {df[col].unique().tolist()}")

## Kiểm tra nội dung các cột `target`

In [ ]:
print(f"{target_col} -> {df[target_col].unique().tolist()}")

temp_bin_target -> ['low', 'medium', 'high']

## Fill missing value

In [ ]:
preprocessor = ColumnTransformer(
    transformers=[
        ("num", SimpleImputer(strategy="mean"), numeric_cols),
        ("numCat", SimpleImputer(strategy="most_frequent"), numericCat_cols),
        ("cat", SimpleImputer(strategy="most_frequent"), cat_cols),
        ("target", SimpleImputer(strategy="most_frequent"), [target_col]),
    ]
)

df = preprocessor.fit_transform(df)

df = pd.DataFrame(
    df, columns=numeric_cols + numericCat_cols + cat_cols + [target_col]
)

df.head()

,wind_kph_num,wind_degree_num,pressure_in_num,humidity_num,cloud_num,visibility_km_num,uv_index_num,gust_kph_num,air_quality_Carbon_Monoxide_num,air_quality_Ozone_num,air_quality_Nitrogen_dioxide_num,air_quality_Sulphur_dioxide_num,air_quality_PM2_5_num,air_quality_PM10_num,moon_illumination_num,moon_phase_nom,temp_bin_target
0,18.0,57.0,30.39,81.0,75.0,10.0,1.3,24.2,384.8,52.0,17.205,0.925,21.09,23.495,1.0,Waxing Crescent,low
1,10.1,247.0,30.55,80.0,2.0,10.0,0.3,17.0,362.6,26.0,31.82,0.925,17.575,29.23,37.0,Waxing Crescent,low
2,24.5,75.0,29.83,89.0,100.0,19.0,0.0,33.6,177.6,31.0,0.925,0.925,5.92,9.065,69.0,Waning Gibbous,medium
3,22.3,211.0,30.02,12.0,0.0,10.0,6.0,25.7,240.3,76.5,1.1,3.5,5.7,13.8,5.0,Waning Crescent,low
4,3.6,256.0,29.94,40.0,0.0,10.0,6.0,3.7,264.55,80.0,8.695,6.29,8.14,13.32,71.0,Waning Gibbous,medium

In [ ]:
np.all(df.isnull().sum() == 0)

True

## Chuyển đổi các cột về đúng kiểu dữ liệu

In [ ]:
df[numeric_cols] = df[numeric_cols].astype("float32")
df[numericCat_cols] = df[numericCat_cols].astype("float32")
df[cat_cols] = df[cat_cols].astype("category")
df[target_col] = df[target_col].astype("category")

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52542 entries, 0 to 52541
Data columns (total 17 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   wind_kph_num                      52542 non-null  float32
 1   wind_degree_num                   52542 non-null  float32
 2   pressure_in_num                   52542 non-null  float32
 3   humidity_num                      52542 non-null  float32
 4   cloud_num                         52542 non-null  float32
 5   visibility_km_num                 52542 non-null  float32
 6   uv_index_num                      52542 non-null  float32
 7   gust_kph_num                      52542 non-null  float32
 8   air_quality_Carbon_Monoxide_num   52542 non-null  float32
 9   air_quality_Ozone_num             52542 non-null  float32
 10  air_quality_Nitrogen_dioxide_num  52542 non-null  float32
 11  air_quality_Sulphur_dioxide_num   52542 non-null  float32
 12  air_quality_PM2_5_num             52542 non-null  float32
 13  air_quality_PM10_num              52542 non-null  float32
 14  moon_illumination_num             52542 non-null  float32
 15  moon_phase_nom                    52542 non-null  category
 16  temp_bin_target                   52542 non-null  category
dtypes: category(2), float32(15)
memory usage: 3.1 MB

## Loại bỏ duplicates

In [ ]:
print(f"Tỉ lệ duplicates: {len(df.index[df.duplicated()]) / len(df.index) * 100}" )
df = df.drop_duplicates().reset_index()

0.41109969167523125

## FEATURE_ORDINAL_DICT

In [ ]:
binary_cols + ordinal_cols

[]

In [ ]:
FEATURE_ORDINAL_DICT = {

}

# r

In [4]:
df = myfuncs.load_python_object("artifacts/data_correction_dc2/data.pkl")
transformer = myfuncs.load_python_object("artifacts/data_correction_dc2/transformer.pkl")
feature_ordinal_dict = myfuncs.load_python_object("artifacts/data_correction_dc2/feature_ordinal_dict.pkl")
df.head()

,wind_kph_num,wind_degree_num,pressure_in_num,humidity_num,cloud_num,visibility_km_num,uv_index_num,gust_kph_num,air_quality_Carbon_Monoxide_num,air_quality_Ozone_num,air_quality_Nitrogen_dioxide_num,air_quality_Sulphur_dioxide_num,air_quality_PM2_5_num,air_quality_PM10_num,moon_illumination_num,moon_phase_nom,temp_bin_target
0,18.000000,57.0,30.389999,81.0,75.0,10.0,1.3,24.200001,384.799988,52.0,17.205,0.925,21.090000,23.495001,1.0,Waxing Crescent,low
1,10.100000,247.0,30.549999,80.0,2.0,10.0,0.3,17.000000,362.600006,26.0,31.820,0.925,17.575001,29.230000,37.0,Waxing Crescent,low
2,24.500000,75.0,29.830000,89.0,100.0,19.0,0.0,33.599998,177.600006,31.0,0.925,0.925,5.920000,9.065000,69.0,Waning Gibbous,medium
3,22.299999,211.0,30.020000,12.0,0.0,10.0,6.0,25.700001,240.300003,76.5,1.100,3.500,5.700000,13.800000,5.0,Waning Crescent,low
4,3.600000,256.0,29.940001,40.0,0.0,10.0,6.0,3.700000,264.549988,80.0,8.695,6.290,8.140000,13.320000,71.0,Waning Gibbous,medium

In [5]:
numeric_cols = myfuncs.get_different_types_cols_from_df_4(df)[0]
numericcat_cols = myfuncs.get_different_types_cols_from_df_4(df)[1]

df[numeric_cols].describe().loc[['min', 'max']].T

                                          min           max
wind_kph_num                         3.600000   2963.199951
wind_degree_num                      1.000000    360.000000
pressure_in_num                     27.959999     88.589996
humidity_num                         2.000000    100.000000
cloud_num                            0.000000    100.000000
visibility_km_num                    0.000000     32.000000
uv_index_num                         0.000000     16.299999
gust_kph_num                         3.600000   2970.399902
air_quality_Carbon_Monoxide_num  -9999.000000  38879.398438
air_quality_Ozone_num                0.000000    480.700012
air_quality_Nitrogen_dioxide_num     0.000000    427.700012
air_quality_Sulphur_dioxide_num  -9999.000000    521.330017
air_quality_PM2_5_num                0.185000   1614.099976
air_quality_PM10_num                 0.185000   5899.279785
moon_illumination_num                0.000000    100.000000

cột air_quality_Carbon_Monoxide_num có giá trị min < 0

cột air_quality_Sulphur_dioxide_num có giá trị min < 0

Fill các giá trị < 0 của 2 cột bằng median

In [7]:
col_names = ["air_quality_Carbon_Monoxide_num", "air_quality_Sulphur_dioxide_num"]

for col in col_names:
  df[col][df.index[df[col] < 0]] = np.percentile(df[col], 50)

df[numeric_cols].describe().loc[['min', 'max']].T

<ipython-input-7-2b864edab658>:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df[col][df.index[df[col] < 0]] = np.percentile(df[col], 50)
<ipython-input-7-2b864edab658>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col][df.index[df[col] < 0]] = np.percentile(df[col], 50)

                                        min           max
wind_kph_num                       3.600000   2963.199951
wind_degree_num                    1.000000    360.000000
pressure_in_num                   27.959999     88.589996
humidity_num                       2.000000    100.000000
cloud_num                          0.000000    100.000000
visibility_km_num                  0.000000     32.000000
uv_index_num                       0.000000     16.299999
gust_kph_num                       3.600000   2970.399902
air_quality_Carbon_Monoxide_num   81.000000  38879.398438
air_quality_Ozone_num              0.000000    480.700012
air_quality_Nitrogen_dioxide_num   0.000000    427.700012
air_quality_Sulphur_dioxide_num    0.000000    521.330017
air_quality_PM2_5_num              0.185000   1614.099976
air_quality_PM10_num               0.185000   5899.279785
moon_illumination_num              0.000000    100.000000

In [10]:
subplot_titles = sum(([item, "", ""] for item in numeric_cols), [])

fig = make_subplots(rows=len(numeric_cols), cols=3, subplot_titles=subplot_titles)

for row, col in enumerate(numeric_cols, 1):
    data = df[col]

    # Vẽ Histogram
    fig_hist = px.histogram(
        x=data,
        nbins=100,
    )

    # Thêm đường viền cho các cột histogram
    fig_hist.update_traces(marker=dict(line=dict(width=1, color="black")))

    # Vẽ box plot
    fig_box = px.box(
        y=data,
    )

    # Vẽ violin plot
    fig_violin = px.violin(
        y=data,
        box=True,
    )

    fig.add_trace(fig_hist.data[0], row=row, col=1)
    fig.add_trace(fig_box.data[0], row=row, col=2)
    fig.add_trace(fig_violin.data[0], row=row, col=3)

fig.update_layout(
    width=400 * 3,  # Độ rộng biểu đồ (px)
    height=len(numeric_cols) * 500,  # Độ cao biểu đồ (px)
)

fig.show()

Output hidden; open in https://colab.research.google.com to view.

cột wind_kph_num bị lệch trên

cột wind_degree_num đều

cột pressure_in_num bị lệch trên

cột humidity_num đều

cột cloud_num đều

cột visibility_km_num bị lệch 2 bên

cột uv_index_num đều

cột gust_kph_num bị lệch trên

cột air_quality_Carbon_Monoxide_num  bị lệch trên

cột air_quality_Ozone_num bị lệch trên

cột air_quality_Nitrogen_dioxide_num  bị lệch trên

cột air_quality_Sulphur_dioxide_num bị lệch trên

cột air_quality_PM2_5_num bị lệch trên

cột air_quality_PM10_num bị lệch trên

cột moon_illumination_num đều

Fill các giá trị outliers của các cột wind_kph_num, pressure_in_num, visibility_km_num, gust_kph_num, air_quality_Carbon_Monoxide_num, air_quality_Ozone_num, air_quality_Nitrogen_dioxide_num, air_quality_Sulphur_dioxide_num, air_quality_PM2_5_num, air_quality_PM10_num bằng median của cột

In [11]:
col_names = [
    'wind_kph_num',
    'pressure_in_num',
    'visibility_km_num',
    'gust_kph_num',
    'air_quality_Carbon_Monoxide_num',
    'air_quality_Ozone_num',
    'air_quality_Nitrogen_dioxide_num',
    'air_quality_Sulphur_dioxide_num',
    'air_quality_PM2_5_num',
    'air_quality_PM10_num',
]

for col_name in col_names:
  df[col_name] = myfuncs.replace_outliers_with_new_value_34(df[col_name], np.percentile(df[col_name], 50))

/usr/local/lib/python3.11/dist-packages/Mylib/myfuncs.py:1607: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [12]:
subplot_titles = sum(([item, "", ""] for item in numeric_cols), [])

fig = make_subplots(rows=len(numeric_cols), cols=3, subplot_titles=subplot_titles)

for row, col in enumerate(numeric_cols, 1):
    data = df[col]

    # Vẽ Histogram
    fig_hist = px.histogram(
        x=data,
        nbins=100,
    )

    # Thêm đường viền cho các cột histogram
    fig_hist.update_traces(marker=dict(line=dict(width=1, color="black")))

    # Vẽ box plot
    fig_box = px.box(
        y=data,
    )

    # Vẽ violin plot
    fig_violin = px.violin(
        y=data,
        box=True,
    )

    fig.add_trace(fig_hist.data[0], row=row, col=1)
    fig.add_trace(fig_box.data[0], row=row, col=2)
    fig.add_trace(fig_violin.data[0], row=row, col=3)

fig.update_layout(
    width=400 * 3,  # Độ rộng biểu đồ (px)
    height=len(numeric_cols) * 500,  # Độ cao biểu đồ (px)
)

fig.show()

Output hidden; open in https://colab.research.google.com to view.

In [13]:
for col in numericcat_cols:
  print(f"{col} -> {df[col].unique().tolist()}")

In [17]:
df.shape

(52326, 17)

In [16]:
# Lưu dữ liệu
folder = "artifacts/data_correction_dc3"
os.makedirs(folder, exist_ok=True)

myfuncs.save_python_object(os.path.join(folder, "data.pkl"), df)
myfuncs.save_python_object(os.path.join(folder, "transformer.pkl"), transformer)
myfuncs.save_python_object(os.path.join(folder, "feature_ordinal_dict.pkl"), feature_ordinal_dict)

# r

In [18]:
df = myfuncs.load_python_object("artifacts/data_correction_dc1/data.pkl")

df.head()

,wind_kph_num,wind_degree_num,pressure_in_num,humidity_num,cloud_num,visibility_km_num,uv_index_num,gust_kph_num,air_quality_Carbon_Monoxide_num,air_quality_Ozone_num,...,air_quality_Sulphur_dioxide_num,air_quality_PM2_5_num,air_quality_PM10_num,moon_illumination_num,moon_phase_nom,sunrise_ord,sunset_ord,moonrise_ord,moonset_ord,temp_bin_target
0,18.000000,57.0,30.389999,81.0,75.0,10.0,1.3,24.200001,384.799988,52.0,...,0.925,21.090000,23.495001,1.0,Waxing Crescent,07,18,07,20,low
1,10.100000,247.0,30.549999,80.0,2.0,10.0,0.3,17.000000,362.600006,26.0,...,0.925,17.575001,29.230000,37.0,Waxing Crescent,07,15,14,20,low
2,24.500000,75.0,29.830000,89.0,100.0,19.0,0.0,33.599998,177.600006,31.0,...,0.925,5.920000,9.065000,69.0,Waning Gibbous,06,18,23,10,medium
3,22.299999,211.0,30.020000,12.0,0.0,10.0,6.0,25.700001,240.300003,76.5,...,3.500,5.700000,13.800000,5.0,Waning Crescent,06,17,05,15,low
4,3.600000,256.0,29.940001,40.0,0.0,10.0,6.0,3.700000,264.549988,80.0,...,6.290,8.140000,13.320000,71.0,Waning Gibbous,05,19,01,09,medium

| Cot                       | Y nghia                                                               | Don vi | Phan loai |
| ------------------------- | --------------------------------------------------------------------- | ------ | --------- |
| wind_kph         | Tốc độ gió (km / hour)      | none   | numeric   |
| wind_degree        | Hướng gió theo độ    | none   | numeric   |
| pressure_in         | Áp suất (inches)    | none   | numeric   |
| humidity         | Độ ẩm (%)    | none   | numeric   |
| cloud         | Phần trăm mây bao phủ (%)    | none   | numeric   |
| visibility_km         | Tầm nhìn (km)    | none   | numeric   |
| uv_index         | Chỉ số tia UV    | none   | numeric   |
| gust_kph         | sự tăng tốc đột ngột và mạnh mẽ của gió (km / h)    | none   | numeric   |
| air_quality_Carbon_Monoxide         | Nồng độ $CO$    | none   | numeric   |
| air_quality_Ozone         | Nồng độ $O_3$    | none   | numeric   |
| air_quality_Nitrogen_dioxide         | Nồng độ $NO_2$    | none   | numeric   |
| air_quality_Sulphur_dioxide         | Nồng độ $SO_2$    | none   | numeric   |
| air_quality_PM2.5         | Nồng độ $PM2.5$    | none   | numeric   |
| air_quality_PM10         | Nồng độ $PM10$    | none   | numeric   |
| sunrise         | Thời điểm mặt trời lên   | none   | ordinal   |
| sunset         | Thời điểm mặt trời lặn   | none   | ordinal   |
| moonrise         | Thời điểm trăng lên   | none   | ordinal   |
| moonset         | Thời điểm trăng lặn   | none   | ordinal   |
| moon_phase         | Pha của mặt trăng   | none   | nominal   |
| moon_illumination         | Độ sáng của mặt trăng (%)   | none   | numeric |

In [20]:
df.columns

Index(['wind_kph_num', 'wind_degree_num', 'pressure_in_num', 'humidity_num',
       'cloud_num', 'visibility_km_num', 'uv_index_num', 'gust_kph_num',
       'air_quality_Carbon_Monoxide_num', 'air_quality_Ozone_num',
       'air_quality_Nitrogen_dioxide_num', 'air_quality_Sulphur_dioxide_num',
       'air_quality_PM2_5_num', 'air_quality_PM10_num',
       'moon_illumination_num', 'moon_phase_nom', 'sunrise_ord', 'sunset_ord',
       'moonrise_ord', 'moonset_ord', 'temp_bin_target'],
      dtype='object')

Bỏ 2 cột sunset, moonset

In [21]:
df = df.drop(columns = ['sunset_ord', 'moonset_ord'])

In [22]:
ordinal_cols = myfuncs.get_different_types_cols_from_df_4(df)[5]
ordinal_cols

['sunrise_ord', 'moonrise_ord']

In [23]:
for col in ordinal_cols:
  print(f"{col} -> {df[col].unique().tolist()}")

sunrise_ord -> ['07', '06', '05', '04', '08', '03', '09', '10', '11', '02']
moonrise_ord -> ['07', '14', '23', '05', '01', '18', '20', '03', '08', '24', 'No moonrise', '22', '21', '16', '11', '10', '09', '12', '04', '02', '06', '19', '13', '17', '15']

In [25]:
col_name = 'sunrise_ord'
replace_value = [
    [['02', '03', '04', '05'], 'early_morning'],
    [['06','07', '08', '09' ], 'morning'],
    [['10', '11'], 'midday']
]
df[col_name] = myfuncs.replace_in_category_series_33(df[col_name], replace_value)
df[col_name].unique()

['morning', 'early_morning', 'midday']
Categories (3, string): [early_morning, midday, morning]

In [28]:
a = df['moonrise_ord'].unique().tolist()
a

['07',
 '14',
 '23',
 '05',
 '01',
 '18',
 '20',
 '03',
 '08',
 '24',
 'No moonrise',
 '22',
 '21',
 '16',
 '11',
 '10',
 '09',
 '12',
 '04',
 '02',
 '06',
 '19',
 '13',
 '17',
 '15']

In [29]:
col_name = 'moonrise_ord'
replace_value = [
    [['02','03', '04', '05'], 'early_morning'],
    [['06','07', '08', '09'], 'morning'],
    [['10','11', '12', '13'], 'midday'],
    [['14','15', '16', '17'], 'afternoon'],
    [['18','19', '20', '21', '22'], 'evening'],
    [['23','24', '01'], 'midnight'],
]
df[col_name] = myfuncs.replace_in_category_series_33(df[col_name], replace_value)
df[col_name].unique()

['morning', 'afternoon', 'midnight', 'early_morning', 'evening', 'No moonrise', 'midday']
Categories (7, string): [No moonrise, afternoon, early_morning, evening, midday, midnight, morning]

In [30]:
numeric_cols = myfuncs.get_different_types_cols_from_df_4(df)[0]

In [31]:
df[numeric_cols].describe().loc[['min', 'max']].T

                                          min           max
wind_kph_num                         3.600000   2963.199951
wind_degree_num                      1.000000    360.000000
pressure_in_num                     27.959999     88.589996
humidity_num                         2.000000    100.000000
cloud_num                            0.000000    100.000000
visibility_km_num                    0.000000     32.000000
uv_index_num                         0.000000     16.299999
gust_kph_num                         3.600000   2970.399902
air_quality_Carbon_Monoxide_num  -9999.000000  38879.398438
air_quality_Ozone_num                0.000000    480.700012
air_quality_Nitrogen_dioxide_num     0.000000    427.700012
air_quality_Sulphur_dioxide_num  -9999.000000    521.330017
air_quality_PM2_5_num                0.185000   1614.099976
air_quality_PM10_num                 0.185000   5899.279785
moon_illumination_num                0.000000    100.000000

Fill các giá trị < 0 của 2 cột air_quality_Carbon_Monoxide_num và air_quality_Sulphur_dioxide_num bằng median

In [32]:
col_names = ["air_quality_Carbon_Monoxide_num", "air_quality_Sulphur_dioxide_num"]

for col in col_names:
  df.loc[df.index[df[col] < 0], col] = np.percentile(df[col], 50)

df[numeric_cols].describe().loc[['min', 'max']].T

                                        min           max
wind_kph_num                       3.600000   2963.199951
wind_degree_num                    1.000000    360.000000
pressure_in_num                   27.959999     88.589996
humidity_num                       2.000000    100.000000
cloud_num                          0.000000    100.000000
visibility_km_num                  0.000000     32.000000
uv_index_num                       0.000000     16.299999
gust_kph_num                       3.600000   2970.399902
air_quality_Carbon_Monoxide_num   81.000000  38879.398438
air_quality_Ozone_num              0.000000    480.700012
air_quality_Nitrogen_dioxide_num   0.000000    427.700012
air_quality_Sulphur_dioxide_num    0.000000    521.330017
air_quality_PM2_5_num              0.185000   1614.099976
air_quality_PM10_num               0.185000   5899.279785
moon_illumination_num              0.000000    100.000000

Fill các giá trị outliers của các cột wind_kph_num, pressure_in_num, visibility_km_num, gust_kph_num, air_quality_Carbon_Monoxide_num, air_quality_Ozone_num, air_quality_Nitrogen_dioxide_num, air_quality_Sulphur_dioxide_num, air_quality_PM2_5_num, air_quality_PM10_num bằng median của cột

In [33]:
col_names = [
    'wind_kph_num',
    'pressure_in_num',
    'visibility_km_num',
    'gust_kph_num',
    'air_quality_Carbon_Monoxide_num',
    'air_quality_Ozone_num',
    'air_quality_Nitrogen_dioxide_num',
    'air_quality_Sulphur_dioxide_num',
    'air_quality_PM2_5_num',
    'air_quality_PM10_num',
]

for col_name in col_names:
  df[col_name] = myfuncs.replace_outliers_with_new_value_34(df[col_name], np.percentile(df[col_name], 50))

/usr/local/lib/python3.11/dist-packages/Mylib/myfuncs.py:1607: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

# dc4

## Đọc dữ liệu

In [69]:
df = myfuncs.load_python_object("artifacts/data_ingestion/train_data.pkl")

df.head()

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination,temp_bin
56032,Luxembourg,Luxembourg,49.6117,6.1300,Europe/Luxembourg,1740822300,2025-03-01 10:45,3.0,37.4,Partly cloudy,...,23.495,2,2,07:18 AM,06:18 PM,07:55 AM,08:30 PM,Waxing Crescent,1,low
34107,Sweden,Stockholm,59.3333,18.0500,Europe/Stockholm,1731056400,2024-11-08 10:00,7.3,45.1,Sunny,...,29.230,2,2,07:26 AM,03:37 PM,02:20 PM,08:48 PM,Waxing Crescent,37,low
54115,Palau,Airai,7.3575,134.5578,Pacific/Palau,1739960100,2025-02-19 19:15,27.3,81.1,Overcast,...,9.065,1,1,06:18 AM,06:13 PM,11:15 PM,10:29 AM,Waning Gibbous,69,medium
9861,South Africa,Pretoria,-25.7500,28.1900,Africa/Johannesburg,1720098900,2024-07-04 15:15,19.1,66.4,Sunny,...,13.800,1,1,06:54 AM,05:29 PM,05:33 AM,03:57 PM,Waning Crescent,5,low
65611,Macedonia,Skopje,42.0000,21.4333,Europe/Skopje,1745053200,2025-04-19 11:00,21.3,70.3,Partly Cloudy,...,13.320,1,1,05:48 AM,07:20 PM,01:04 AM,09:27 AM,Waning Gibbous,71,medium

## Ý nghĩa các cột

| Cot                       | Y nghia                                                               | Don vi | Phan loai |
| ------------------------- | --------------------------------------------------------------------- | ------ | --------- |
| **country**                     | Đất nước mà dữ liệu được đo                                     | none   | Nominal   |
| **location_name**                       | Tên thành phố                                                          | none   | Nominal   |
| **latitude**             | vĩ độ của thành phố                                                        | none   | ordinal   |
| **longitude**             | kinh độ của thành phố                                                        | none   | ordinal   |
| **timezone**             | Giờ khu vực                                                        | none   | ordinal   |
| **last_updated_epoch**            |  thời điểm cập nhật dữ liệu cuối cùng dưới dạng Unix timestamp.       | none   | ordinal   |
| **last_updated**            |  thời điểm cập nhật dữ liệu cuối cùng (local time)       | none   | ordinal   |
| **temperature_celsius**            |  nhiệt độ dưới dạng C       | none   | ordinal   |
| **temperature_fahrenheit**            |  nhiệt độ dưới dạng F      | none   | ordinal   |
| **condition_text**            |  Tình trạng thời tiết      | none   | ordinal   |
| **wind_mph**         | Tốc độ gió (mile / hour)      | none   | ordinal   |
| wind_kph         | Tốc độ gió (km / hour)      | none   | numeric   |
| wind_degree        | Hướng gió theo độ    | none   | numeric   |
| **wind_direction**         | Hướng gió chi tiết hơn     | none   | numeric   |
| **pressure_mb**         | Áp suất (milibars)    | none   | numeric   |
| pressure_in         | Áp suất (inches)    | none   | numeric   |
| **precip_mm**         | Lượng mưa (mm)    | none   | numeric   |
| **precip_in**         | Lượng mưa (inches)    | none   | numeric   |
| humidity         | Độ ẩm (%)    | none   | numeric   |
| cloud         | Phần trăm mây bao phủ (%)    | none   | numeric   |
| **feels_like_celsius**         | Nhiệt độ cơ thể cảm nhận được thay vì là thực tế    | none   | numeric   |
| **feels_like_fahrenheit**         | Nhiệt độ cơ thể cảm nhận được thay vì là thực tế    | none   | numeric   |
| visibility_km         | Tầm nhìn (km)    | none   | numeric   |
| **visibility_miles**         | Tầm nhìn (mile)    | none   | numeric   |
| uv_index         | Chỉ số tia UV    | none   | numeric   |
| **gust_mph**         | sự tăng tốc đột ngột và mạnh mẽ của gió (mile / h)    | none   | numeric   |
| gust_kph         | sự tăng tốc đột ngột và mạnh mẽ của gió (km / h)    | none   | numeric   |
| air_quality_Carbon_Monoxide         | Nồng độ $CO$    | none   | numeric   |
| air_quality_Ozone         | Nồng độ $O_3$    | none   | numeric   |
| air_quality_Nitrogen_dioxide         | Nồng độ $NO_2$    | none   | numeric   |
| air_quality_Sulphur_dioxide         | Nồng độ $SO_2$    | none   | numeric   |
| air_quality_PM2.5         | Nồng độ $PM2.5$    | none   | numeric   |
| air_quality_PM10         | Nồng độ $PM10$    | none   | numeric   |
| **air_quality_us-epa-index**         | Chỉ số AQI    | none   | numeric   |
| **air_quality_gb-defra-index**         | Chỉ số AQI    | none   | numeric   |
| sunrise         | Thời điểm mặt trời lên   | none   | ordinal   |
| sunset         | Thời điểm mặt trời lặn   | none   | ordinal   |
| moonrise         | Thời điểm trăng lên   | none   | ordinal   |
| moonset         | Thời điểm trăng lặn   | none   | ordinal   |
| moon_phase         | Pha của mặt trăng   | none   | nominal   |
| moon_illumination         | Độ sáng của mặt trăng (%)   | none   | numeric |

## Xóa các cột không cần thiết

### Xóa các cột

In [70]:
df = df.drop(
    columns=[
        "country",
        "location_name",
        "latitude",
        "longitude",
        "timezone",
        "last_updated_epoch",
        "last_updated",
        "temperature_celsius",
        "temperature_fahrenheit",
        "condition_text",
        "wind_mph",
        "wind_direction",
        "pressure_mb",
        "precip_mm",
        "precip_in",
        "feels_like_celsius",
        "feels_like_fahrenheit",
        "visibility_miles",
        "gust_mph",
        "air_quality_us-epa-index",
        "air_quality_gb-defra-index",
        'sunset',
        'moonset'
    ]
)

df.columns

Index(['wind_kph', 'wind_degree', 'pressure_in', 'humidity', 'cloud',
       'visibility_km', 'uv_index', 'gust_kph', 'air_quality_Carbon_Monoxide',
       'air_quality_Ozone', 'air_quality_Nitrogen_dioxide',
       'air_quality_Sulphur_dioxide', 'air_quality_PM2.5', 'air_quality_PM10',
       'sunrise', 'moonrise', 'moon_phase', 'moon_illumination', 'temp_bin'],
      dtype='object')

### Tỉ lệ missing các cột

In [71]:
null_percent = df.isnull().mean() * 100
null_percent = null_percent.sort_values(ascending=False)
null_percent

wind_kph                        0.0
air_quality_Nitrogen_dioxide    0.0
moon_illumination               0.0
moon_phase                      0.0
moonrise                        0.0
sunrise                         0.0
air_quality_PM10                0.0
air_quality_PM2.5               0.0
air_quality_Sulphur_dioxide     0.0
air_quality_Ozone               0.0
wind_degree                     0.0
air_quality_Carbon_Monoxide     0.0
gust_kph                        0.0
uv_index                        0.0
visibility_km                   0.0
cloud                           0.0
humidity                        0.0
pressure_in                     0.0
temp_bin                        0.0
dtype: float64

### Xóa các cột có tỉ lệ missing lớn

Ti le missing của các cột đều = 0-> Khong xoa cot nao het !

## Đổi tên cột

In [72]:
rename_dict = {
    "wind_kph": "wind_kph_num",
    "wind_degree": "wind_degree_num",
    "pressure_in": "pressure_in_num",
    "humidity": "humidity_num",
    "cloud": "cloud_num",
    "visibility_km": "visibility_km_num",
    "uv_index": "uv_index_num",
    "gust_kph": "gust_kph_num",
    "air_quality_Carbon_Monoxide": "air_quality_Carbon_Monoxide_num",
    "air_quality_Ozone": "air_quality_Ozone_num",
    "air_quality_Nitrogen_dioxide": "air_quality_Nitrogen_dioxide_num",
    "air_quality_Sulphur_dioxide": "air_quality_Sulphur_dioxide_num",
    "air_quality_PM2.5": "air_quality_PM2_5_num",
    "air_quality_PM10": "air_quality_PM10_num",
    "sunrise": "sunrise_ord",
    "moonrise": "moonrise_ord",
    "moon_phase": "moon_phase_nom",
    "moon_illumination": "moon_illumination_num",
    "temp_bin": "temp_bin_target",

}


df = df.rename(columns=rename_dict)

df.columns

Index(['wind_kph_num', 'wind_degree_num', 'pressure_in_num', 'humidity_num',
       'cloud_num', 'visibility_km_num', 'uv_index_num', 'gust_kph_num',
       'air_quality_Carbon_Monoxide_num', 'air_quality_Ozone_num',
       'air_quality_Nitrogen_dioxide_num', 'air_quality_Sulphur_dioxide_num',
       'air_quality_PM2_5_num', 'air_quality_PM10_num', 'sunrise_ord',
       'moonrise_ord', 'moon_phase_nom', 'moon_illumination_num',
       'temp_bin_target'],
      dtype='object')

## Sắp xếp các cột theo đúng thứ tự

In [73]:
numeric_cols, numericCat_cols, cat_cols, binary_cols, nominal_cols, ordinal_cols, target_col = myfuncs.get_different_types_cols_from_df_4(df)


df = df[
    numeric_cols
    + numericCat_cols
    + binary_cols
    + nominal_cols
    + ordinal_cols
    + [target_col]
]


df.head()

,wind_kph_num,wind_degree_num,pressure_in_num,humidity_num,cloud_num,visibility_km_num,uv_index_num,gust_kph_num,air_quality_Carbon_Monoxide_num,air_quality_Ozone_num,air_quality_Nitrogen_dioxide_num,air_quality_Sulphur_dioxide_num,air_quality_PM2_5_num,air_quality_PM10_num,moon_illumination_num,moon_phase_nom,sunrise_ord,moonrise_ord,temp_bin_target
56032,18.0,57,30.39,81,75,10.0,1.3,24.2,384.80,52.0,17.205,0.925,21.090,23.495,1,Waxing Crescent,07:18 AM,07:55 AM,low
34107,10.1,247,30.55,80,2,10.0,0.3,17.0,362.60,26.0,31.820,0.925,17.575,29.230,37,Waxing Crescent,07:26 AM,02:20 PM,low
54115,24.5,75,29.83,89,100,19.0,0.0,33.6,177.60,31.0,0.925,0.925,5.920,9.065,69,Waning Gibbous,06:18 AM,11:15 PM,medium
9861,22.3,211,30.02,12,0,10.0,6.0,25.7,240.30,76.5,1.100,3.500,5.700,13.800,5,Waning Crescent,06:54 AM,05:33 AM,low
65611,3.6,256,29.94,40,0,10.0,6.0,3.7,264.55,80.0,8.695,6.290,8.140,13.320,71,Waning Gibbous,05:48 AM,01:04 AM,medium

## Kiểm tra kiểu dữ liệu các cột

In [74]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 52542 entries, 56032 to 4001
Data columns (total 19 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   wind_kph_num                      52542 non-null  float64
 1   wind_degree_num                   52542 non-null  int64
 2   pressure_in_num                   52542 non-null  float64
 3   humidity_num                      52542 non-null  int64
 4   cloud_num                         52542 non-null  int64
 5   visibility_km_num                 52542 non-null  float64
 6   uv_index_num                      52542 non-null  float64
 7   gust_kph_num                      52542 non-null  float64
 8   air_quality_Carbon_Monoxide_num   52542 non-null  float64
 9   air_quality_Ozone_num             52542 non-null  float64
 10  air_quality_Nitrogen_dioxide_num  52542 non-null  float64
 11  air_quality_Sulphur_dioxide_num   52542 non-null  float64
 12  air_quality_PM2_5_num             52542 non-null  float64
 13  air_quality_PM10_num              52542 non-null  float64
 14  moon_illumination_num             52542 non-null  int64
 15  moon_phase_nom                    52542 non-null  object
 16  sunrise_ord                       52542 non-null  object
 17  moonrise_ord                      52542 non-null  object
 18  temp_bin_target                   52542 non-null  category
dtypes: category(1), float64(11), int64(4), object(3)
memory usage: 9.7+ MB

Các cột từ 15 trở đi sai

### Chuyển kdl = kdl mong muốn + NAN

In [75]:
for col in df.columns.tolist()[15:]:
  print(f"{col} -> {set(map(type, df[col]))}")

moon_phase_nom -> {<class 'str'>}
sunrise_ord -> {<class 'str'>}
moonrise_ord -> {<class 'str'>}
temp_bin_target -> {<class 'str'>}

Tất cả các cột đều đúng kiểu dữ liệu

## Kiểm tra nội dung các cột `binary`

In [76]:
for col in binary_cols:
  print(f"{col} -> {df[col].unique().tolist()}")

Không có cột nào hết

## Kiểm tra nội dung các cột `nominal`

In [77]:
for col in nominal_cols:
    print(f"{col} -> {df[col].unique().tolist()}")

moon_phase_nom -> ['Waxing Crescent', 'Waning Gibbous', 'Waning Crescent', 'Last Quarter', 'Waxing Gibbous', 'First Quarter', 'Full Moon', 'New Moon']

## Kiểm tra nội dung các cột `ordinal`

In [78]:
for col in ordinal_cols:
    print(f"{col} -> {df[col].unique().tolist()}")

sunrise_ord -> ['07:18 AM', '07:26 AM', '06:18 AM', '06:54 AM', '05:48 AM', '05:45 AM', '07:13 AM', '06:31 AM', '05:32 AM', '06:14 AM', '05:17 AM', '06:03 AM', '06:52 AM', '06:40 AM', '06:41 AM', '06:50 AM', '05:16 AM', '07:30 AM', '07:56 AM', '06:22 AM', '05:38 AM', '07:17 AM', '06:42 AM', '06:57 AM', '05:33 AM', '06:20 AM', '05:41 AM', '05:23 AM', '06:07 AM', '05:57 AM', '06:00 AM', '04:56 AM', '08:43 AM', '06:13 AM', '05:19 AM', '06:34 AM', '07:22 AM', '04:44 AM', '06:19 AM', '06:09 AM', '05:22 AM', '05:30 AM', '06:05 AM', '05:59 AM', '05:54 AM', '06:27 AM', '05:42 AM', '06:12 AM', '07:45 AM', '06:48 AM', '05:40 AM', '06:32 AM', '06:53 AM', '07:19 AM', '05:56 AM', '05:49 AM', '06:17 AM', '07:03 AM', '06:37 AM', '06:08 AM', '06:16 AM', '07:37 AM', '06:43 AM', '07:16 AM', '06:38 AM', '06:01 AM', '05:18 AM', '05:36 AM', '06:39 AM', '05:39 AM', '05:43 AM', '07:54 AM', '04:06 AM', '07:05 AM', '07:31 AM', '07:59 AM', '07:42 AM', '07:50 AM', '06:45 AM', '05:21 AM', '06:06 AM', '05:51 AM', '04:55 AM', '07:07 AM', '06:24 AM', '05:37 AM', '07:41 AM', '05:25 AM', '06:15 AM', '06:29 AM', '06:11 AM', '07:08 AM', '08:10 AM', '06:55 AM', '07:51 AM', '05:55 AM', '06:23 AM', '06:35 AM', '07:10 AM', '07:20 AM', '05:04 AM', '06:30 AM', '05:29 AM', '07:38 AM', '04:53 AM', '07:55 AM', '05:26 AM', '05:28 AM', '08:58 AM', '04:38 AM', '08:03 AM', '06:44 AM', '08:07 AM', '07:09 AM', '07:33 AM', '05:09 AM', '07:01 AM', '08:33 AM', '06:33 AM', '04:30 AM', '07:11 AM', '06:02 AM', '08:42 AM', '06:21 AM', '06:28 AM', '06:47 AM', '04:49 AM', '07:04 AM', '08:30 AM', '05:35 AM', '05:12 AM', '04:52 AM', '07:25 AM', '04:43 AM', '05:52 AM', '08:22 AM', '06:58 AM', '06:04 AM', '05:27 AM', '05:58 AM', '07:27 AM', '05:46 AM', '04:46 AM', '06:46 AM', '07:23 AM', '06:10 AM', '06:26 AM', '05:47 AM', '07:29 AM', '07:32 AM', '05:13 AM', '07:39 AM', '07:06 AM', '07:44 AM', '07:00 AM', '05:50 AM', '08:06 AM', '07:40 AM', '06:56 AM', '05:15 AM', '05:06 AM', '06:25 AM', '08:00 AM', '05:03 AM', '07:02 AM', '07:49 AM', '05:53 AM', '07:12 AM', '04:45 AM', '08:21 AM', '08:59 AM', '03:59 AM', '07:24 AM', '07:15 AM', '06:36 AM', '04:13 AM', '04:16 AM', '05:31 AM', '06:51 AM', '07:53 AM', '08:02 AM', '05:44 AM', '05:20 AM', '05:08 AM', '04:07 AM', '06:49 AM', '06:59 AM', '03:07 AM', '08:01 AM', '04:57 AM', '08:56 AM', '04:51 AM', '04:59 AM', '08:35 AM', '05:34 AM', '04:48 AM', '07:36 AM', '08:27 AM', '07:48 AM', '05:07 AM', '08:28 AM', '05:14 AM', '05:11 AM', '07:46 AM', '08:23 AM', '08:14 AM', '08:54 AM', '07:43 AM', '09:37 AM', '07:21 AM', '08:08 AM', '07:14 AM', '07:57 AM', '07:35 AM', '08:19 AM', '05:10 AM', '05:24 AM', '08:17 AM', '08:15 AM', '07:28 AM', '03:57 AM', '08:04 AM', '07:34 AM', '08:20 AM', '05:05 AM', '08:51 AM', '07:47 AM', '05:02 AM', '08:16 AM', '04:20 AM', '08:29 AM', '07:58 AM', '08:24 AM', '08:26 AM', '07:52 AM', '04:31 AM', '09:18 AM', '04:03 AM', '03:58 AM', '09:20 AM', '04:58 AM', '09:28 AM', '04:36 AM', '09:58 AM', '03:40 AM', '09:27 AM', '09:06 AM', '08:32 AM', '08:13 AM', '04:26 AM', '08:37 AM', '04:37 AM', '08:18 AM', '05:00 AM', '04:08 AM', '04:54 AM', '03:55 AM', '08:31 AM', '08:48 AM', '04:19 AM', '08:05 AM', '04:32 AM', '03:45 AM', '04:29 AM', '04:40 AM', '04:47 AM', '03:54 AM', '08:11 AM', '04:35 AM', '05:01 AM', '04:41 AM', '04:25 AM', '09:08 AM', '08:39 AM', '08:25 AM', '09:10 AM', '08:34 AM', '04:50 AM', '08:41 AM', '08:40 AM', '08:09 AM', '04:10 AM', '08:38 AM', '08:47 AM', '08:50 AM', '08:12 AM', '04:00 AM', '04:01 AM', '10:00 AM', '04:18 AM', '09:25 AM', '08:44 AM', '09:03 AM', '03:32 AM', '08:49 AM', '04:33 AM', '09:12 AM', '03:16 AM', '03:53 AM', '09:01 AM', '04:27 AM', '08:36 AM', '10:06 AM', '11:01 AM', '10:30 AM', '04:14 AM', '09:21 AM', '04:09 AM', '04:28 AM', '04:39 AM', '04:42 AM', '04:11 AM', '03:47 AM', '04:04 AM', '09:16 AM', '08:55 AM', '08:45 AM', '08:52 AM', '04:34 AM', '08:46 AM', '09:07 AM', '09:22 AM', '09:29 AM', '09:17 AM', '04:05 AM', '04:24 AM', '09:26 AM', '10:43 AM', '09:42 AM', '10:08 AM', '04:22 AM', '03:08 AM', '10:35 AM', '03:51 AM', '09:05 AM', '03:15 AM', '03:48 AM', '09:15 AM', '03:09 AM', '09:00 AM', '04:21 AM', '09:23 AM', '04:23 AM', '03:28 AM', '04:12 AM', '08:57 AM', '09:02 AM', '03:42 AM', '03:49 AM', '10:22 AM', '03:50 AM', '10:42 AM', '03:23 AM', '10:29 AM', '10:50 AM', '04:02 AM', '10:55 AM', '09:19 AM', '03:37 AM', '03:33 AM', '09:11 AM', '10:25 AM', '09:13 AM', '11:04 AM', '11:03 AM', '04:17 AM', '10:54 AM', '09:51 AM', '03:14 AM', '09:31 AM', '03:29 AM', '03:05 AM', '10:44 AM', '03:46 AM', '04:15 AM', '03:27 AM', '10:17 AM', '09:24 AM', '10:45 AM', '03:31 AM', '09:52 AM', '03:26 AM', '09:34 AM', '03:56 AM', '08:53 AM', '10:56 AM', '03:12 AM', '10:52 AM', '03:36 AM', '09:55 AM', '03:44 AM', '09:09 AM', '10:48 AM', '09:43 AM', '03:34 AM', '03:19 AM', '10:53 AM', '09:48 AM', '09:35 AM', '10:19 AM', '10:57 AM', '02:58 AM', '10:34 AM', '03:39 AM', '10:59 AM', '09:38 AM', '02:55 AM', '10:27 AM', '10:02 AM', '02:48 AM', '03:41 AM', '10:28 AM', '11:00 AM', '03:06 AM', '09:40 AM', '10:58 AM', '11:02 AM', '10:11 AM', '10:32 AM', '03:38 AM', '03:52 AM', '09:04 AM', '03:43 AM', '09:14 AM', '03:30 AM', '03:25 AM', '10:33 AM', '02:57 AM', '03:21 AM', '09:49 AM', '10:38 AM', '10:46 AM', '03:20 AM', '03:35 AM', '03:11 AM', '10:40 AM', '10:24 AM', '02:49 AM', '02:53 AM', '03:13 AM', '10:14 AM', '10:36 AM', '03:10 AM', '03:18 AM']

In [79]:
# Chuỗi nào có PM thì giá trị giờ cộng thêm 12 phút
def process_time(gold_time: str):
    if gold_time.endswith("PM"):
        parts = gold_time.split(":")
        hour = int(parts[0]) + 12
        gold_time = f"{hour}:{parts[1]}"

    res = re.split("(AM|PM)", gold_time)[0].strip()
    res = res.split(":")[0]
    return res

format = r"\d+:\d+\s*(AM|PM)"

df_ordinal_cols = df[ordinal_cols]
index_not_satisfy_format = (
    df_ordinal_cols[
        df_ordinal_cols.applymap(
            lambda item: re.fullmatch(format, item) is None
        )
    ]
    .stack()
    .index
)

df_ordinal_cols_happen_stack = df_ordinal_cols.stack()
df_ordinal_cols_happen_stack = df_ordinal_cols_happen_stack[
    ~df_ordinal_cols_happen_stack.index.isin(index_not_satisfy_format)
]
df_ordinal_cols_happen_stack = df_ordinal_cols_happen_stack.apply(
    lambda item: process_time(item)
)
df_ordinal_cols_stack = df_ordinal_cols.stack()
df_ordinal_cols_stack[df_ordinal_cols_happen_stack.index] = (
    df_ordinal_cols_happen_stack
)
df[ordinal_cols] = df_ordinal_cols_stack.unstack()

for col in ordinal_cols:
    print(f"{col} -> {df[col].unique().tolist()}")

<ipython-input-79-943485b61a46>:17: FutureWarning:

DataFrame.applymap has been deprecated. Use DataFrame.map instead.

sunrise_ord -> ['07', '06', '05', '04', '08', '03', '09', '10', '11', '02']
moonrise_ord -> ['07', '14', '23', '05', '01', '18', '20', '03', '08', '24', 'No moonrise', '22', '21', '16', '11', '10', '09', '12', '04', '02', '06', '19', '13', '17', '15']

In [80]:
col_name = 'sunrise_ord'
replace_value = [
    [['02', '03', '04', '05'], 'early_morning'],
    [['06','07', '08', '09' ], 'morning'],
    [['10', '11'], 'midday']
]
df[col_name] = myfuncs.replace_in_category_series_33(df[col_name], replace_value)
df[col_name].unique()

['morning', 'early_morning', 'midday']
Categories (3, string): [early_morning, midday, morning]

In [81]:
col_name = 'moonrise_ord'
replace_value = [
    [['02','03', '04', '05'], 'early_morning'],
    [['06','07', '08', '09'], 'morning'],
    [['10','11', '12', '13'], 'midday'],
    [['14','15', '16', '17'], 'afternoon'],
    [['18','19', '20', '21', '22'], 'evening'],
    [['23','24', '01'], 'midnight'],
]
df[col_name] = myfuncs.replace_in_category_series_33(df[col_name], replace_value)
df[col_name].unique()

['morning', 'afternoon', 'midnight', 'early_morning', 'evening', 'No moonrise', 'midday']
Categories (7, string): [No moonrise, afternoon, early_morning, evening, midday, midnight, morning]

## Kiểm tra nội dung các cột `target`

In [82]:
print(f"{target_col} -> {df[target_col].unique().tolist()}")

temp_bin_target -> ['low', 'medium', 'high']

## Fill missing value

In [83]:
preprocessor = ColumnTransformer(
    transformers=[
        ("num", SimpleImputer(strategy="mean"), numeric_cols),
        ("numCat", SimpleImputer(strategy="most_frequent"), numericCat_cols),
        ("cat", SimpleImputer(strategy="most_frequent"), cat_cols),
        ("target", SimpleImputer(strategy="most_frequent"), [target_col]),
    ]
)

df = preprocessor.fit_transform(df)

df = pd.DataFrame(
    df, columns=numeric_cols + numericCat_cols + cat_cols + [target_col]
)

df.head()

,wind_kph_num,wind_degree_num,pressure_in_num,humidity_num,cloud_num,visibility_km_num,uv_index_num,gust_kph_num,air_quality_Carbon_Monoxide_num,air_quality_Ozone_num,air_quality_Nitrogen_dioxide_num,air_quality_Sulphur_dioxide_num,air_quality_PM2_5_num,air_quality_PM10_num,moon_illumination_num,moon_phase_nom,sunrise_ord,moonrise_ord,temp_bin_target
0,18.0,57.0,30.39,81.0,75.0,10.0,1.3,24.2,384.8,52.0,17.205,0.925,21.09,23.495,1.0,Waxing Crescent,morning,morning,low
1,10.1,247.0,30.55,80.0,2.0,10.0,0.3,17.0,362.6,26.0,31.82,0.925,17.575,29.23,37.0,Waxing Crescent,morning,afternoon,low
2,24.5,75.0,29.83,89.0,100.0,19.0,0.0,33.6,177.6,31.0,0.925,0.925,5.92,9.065,69.0,Waning Gibbous,morning,midnight,medium
3,22.3,211.0,30.02,12.0,0.0,10.0,6.0,25.7,240.3,76.5,1.1,3.5,5.7,13.8,5.0,Waning Crescent,morning,early_morning,low
4,3.6,256.0,29.94,40.0,0.0,10.0,6.0,3.7,264.55,80.0,8.695,6.29,8.14,13.32,71.0,Waning Gibbous,early_morning,midnight,medium

## Chuyển đổi các cột về đúng kiểu dữ liệu

In [84]:
df[numeric_cols] = df[numeric_cols].astype("float32")
df[numericCat_cols] = df[numericCat_cols].astype("float32")
df[cat_cols] = df[cat_cols].astype("category")
df[target_col] = df[target_col].astype("category")

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52542 entries, 0 to 52541
Data columns (total 19 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   wind_kph_num                      52542 non-null  float32
 1   wind_degree_num                   52542 non-null  float32
 2   pressure_in_num                   52542 non-null  float32
 3   humidity_num                      52542 non-null  float32
 4   cloud_num                         52542 non-null  float32
 5   visibility_km_num                 52542 non-null  float32
 6   uv_index_num                      52542 non-null  float32
 7   gust_kph_num                      52542 non-null  float32
 8   air_quality_Carbon_Monoxide_num   52542 non-null  float32
 9   air_quality_Ozone_num             52542 non-null  float32
 10  air_quality_Nitrogen_dioxide_num  52542 non-null  float32
 11  air_quality_Sulphur_dioxide_num   52542 non-null  float32
 12  air_quality_PM2_5_num             52542 non-null  float32
 13  air_quality_PM10_num              52542 non-null  float32
 14  moon_illumination_num             52542 non-null  float32
 15  moon_phase_nom                    52542 non-null  category
 16  sunrise_ord                       52542 non-null  category
 17  moonrise_ord                      52542 non-null  category
 18  temp_bin_target                   52542 non-null  category
dtypes: category(4), float32(15)
memory usage: 3.2 MB

## Loại bỏ duplicates

In [85]:
print(f"Tỉ lệ duplicates: {len(df.index[df.duplicated()]) / len(df.index) * 100}" )
df = df.drop_duplicates().reset_index()

Tỉ lệ duplicates: 0.41109969167523125

In [86]:
df.head()

,index,wind_kph_num,wind_degree_num,pressure_in_num,humidity_num,cloud_num,visibility_km_num,uv_index_num,gust_kph_num,air_quality_Carbon_Monoxide_num,air_quality_Ozone_num,air_quality_Nitrogen_dioxide_num,air_quality_Sulphur_dioxide_num,air_quality_PM2_5_num,air_quality_PM10_num,moon_illumination_num,moon_phase_nom,sunrise_ord,moonrise_ord,temp_bin_target
0,0,18.000000,57.0,30.389999,81.0,75.0,10.0,1.3,24.200001,384.799988,52.0,17.205,0.925,21.090000,23.495001,1.0,Waxing Crescent,morning,morning,low
1,1,10.100000,247.0,30.549999,80.0,2.0,10.0,0.3,17.000000,362.600006,26.0,31.820,0.925,17.575001,29.230000,37.0,Waxing Crescent,morning,afternoon,low
2,2,24.500000,75.0,29.830000,89.0,100.0,19.0,0.0,33.599998,177.600006,31.0,0.925,0.925,5.920000,9.065000,69.0,Waning Gibbous,morning,midnight,medium
3,3,22.299999,211.0,30.020000,12.0,0.0,10.0,6.0,25.700001,240.300003,76.5,1.100,3.500,5.700000,13.800000,5.0,Waning Crescent,morning,early_morning,low
4,4,3.600000,256.0,29.940001,40.0,0.0,10.0,6.0,3.700000,264.549988,80.0,8.695,6.290,8.140000,13.320000,71.0,Waning Gibbous,early_morning,midnight,medium

In [87]:
df = df.drop(columns = ['index'])

## FEATURE_ORDINAL_DICT

In [88]:
binary_cols + ordinal_cols

['sunrise_ord', 'moonrise_ord']

In [89]:
df['moonrise_ord'].unique()

['morning', 'afternoon', 'midnight', 'early_morning', 'evening', 'No moonrise', 'midday']
Categories (7, object): ['No moonrise', 'afternoon', 'early_morning', 'evening', 'midday', 'midnight',
                         'morning']

In [90]:
FEATURE_ORDINAL_DICT = {
  "sunrise_ord": ['early_morning', 'morning', 'midday'],
  "moonrise_ord": ['No moonrise', 'early_morning', 'morning', 'midday', 'afternoon', 'evening', 'midnight'],
}

Fill các giá trị < 0 của 2 cột air_quality_Carbon_Monoxide_num và air_quality_Sulphur_dioxide_num bằng median

In [91]:
col_names = ["air_quality_Carbon_Monoxide_num", "air_quality_Sulphur_dioxide_num"]

for col in col_names:
  df.loc[df.index[df[col] < 0], col] = np.percentile(df[col], 50)

df[numeric_cols].describe().loc[['min', 'max']].T

                                        min           max
wind_kph_num                       3.600000   2963.199951
wind_degree_num                    1.000000    360.000000
pressure_in_num                   27.959999     88.589996
humidity_num                       2.000000    100.000000
cloud_num                          0.000000    100.000000
visibility_km_num                  0.000000     32.000000
uv_index_num                       0.000000     16.299999
gust_kph_num                       3.600000   2970.399902
air_quality_Carbon_Monoxide_num   81.000000  38879.398438
air_quality_Ozone_num              0.000000    480.700012
air_quality_Nitrogen_dioxide_num   0.000000    427.700012
air_quality_Sulphur_dioxide_num    0.000000    521.330017
air_quality_PM2_5_num              0.185000   1614.099976
air_quality_PM10_num               0.185000   5899.279785
moon_illumination_num              0.000000    100.000000

Fill các giá trị outliers của các cột wind_kph_num, pressure_in_num, visibility_km_num, gust_kph_num, air_quality_Carbon_Monoxide_num, air_quality_Ozone_num, air_quality_Nitrogen_dioxide_num, air_quality_Sulphur_dioxide_num, air_quality_PM2_5_num, air_quality_PM10_num bằng median của cột

In [92]:
col_names = [
    'wind_kph_num',
    'pressure_in_num',
    'visibility_km_num',
    'gust_kph_num',
    'air_quality_Carbon_Monoxide_num',
    'air_quality_Ozone_num',
    'air_quality_Nitrogen_dioxide_num',
    'air_quality_Sulphur_dioxide_num',
    'air_quality_PM2_5_num',
    'air_quality_PM10_num',
]

for col_name in col_names:
  df[col_name] = myfuncs.replace_outliers_with_new_value_34(df[col_name], np.percentile(df[col_name], 50))

/usr/local/lib/python3.11/dist-packages/Mylib/myfuncs.py:1607: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [94]:
df_copy = myfuncs.load_python_object("artifacts/data_correction_dc4/data.pkl")

fig = px.box(
    y=df_copy['wind_kph_num'],
)

fig.show()

In [93]:
myfuncs.save_python_object("artifacts/data_correction_dc4/data.pkl", df)

# r